import { createContext, useContext, useState, ReactNode } from "react";

// Core languages supported in UI, plus tr/ru for backwards compatibility with data files
export type Language = "en" | "ar" | "ur" | "hi" | "ta" | "te" | "mr" | "bn" | "or" | "ml" | "pa" | "tr" | "ru";

export const LANGUAGES: { code: Language; name: string; nativeName: string; dir: "ltr" | "rtl" }[] = [
  { code: "en", name: "English", nativeName: "English", dir: "ltr" },
  { code: "ar", name: "Arabic", nativeName: "العربية", dir: "rtl" },
  { code: "ur", name: "Urdu", nativeName: "اردو", dir: "rtl" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी", dir: "ltr" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்", dir: "ltr" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు", dir: "ltr" },
  { code: "mr", name: "Marathi", nativeName: "मराठी", dir: "ltr" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা", dir: "ltr" },
  { code: "or", name: "Odia", nativeName: "ଓଡ଼ିଆ", dir: "ltr" },
  { code: "ml", name: "Malayalam", nativeName: "മലയാളം", dir: "ltr" },
  { code: "pa", name: "Punjabi", nativeName: "ਪੰਜਾਬੀ", dir: "ltr" },
];

type TranslationKey = 
  | "hajjGuide"
  | "yourAIGuide"
  | "bismillah"
  | "assalamuAlaikum"
  | "welcomePilgrim"
  | "welcomeSubtitle"
  | "quickQuestions"
  | "tawafSteps"
  | "hajjDuas"
  | "ihramRules"
  | "dayOfArafat"
  | "askPlaceholder"
  | "consultScholar"
  | "newConversation"
  | "yourLocation"
  | "nextStep"
  | "tips"
  | "tryAgain"
  | "unableToLoadMap"
  | "liveMap"
  | "backToChat"
  | "hajjLocations"
  | "familyGroup"
  | "create"
  | "join"
  | "yourName"
  | "groupName"
  | "inviteCode"
  | "cancel"
  | "members"
  | "you"
  | "copied"
  | "inviteLinkCopied"
  | "currentStatus"
  | "statusSafe"
  | "statusAssistance"
  | "statusEmergency"
  | "whatToDoNow"
  | "needHelp"
  | "helpConnecting"
  | "helpConnected"
  | "helpSpeakNow"
  | "helpEndCall"
  | "helpError"
  | "helpTryAgain"
  | "emergency"
  | "emergencyConfirmTitle"
  | "emergencyConfirmDesc"
  | "emergencyConfirm"
  | "preparation"
  | "signIn"
  | "signOut"
  | "noUpdateMeansNormal"
  | "familyStatus"
  | "lastUpdate"
  | "preparationProgress"
  | "stepComplete"
  | "stepPending"
  | "locationStaleWarning"
  | "whatsNewSinceJuly1"
  | "seeFullChangelog";

// Helper type for partial translations in data files - allows missing languages with fallback to English
export type LocalizedString = { en: string } & Partial<Record<Exclude<Language, 'en'>, string>>;

// Helper function to get localized string with English fallback
export function getLocalizedText(translations: LocalizedString, language: Language): string {
  return translations[language] || translations.en;
}

const translations: Partial<Record<Language, Record<TranslationKey, string>>> = {
  en: {
    hajjGuide: "Hajj Guide",
    yourAIGuide: "Your AI Guide",
    bismillah: "Bismillah",
    assalamuAlaikum: "Assalamu Alaikum",
    welcomePilgrim: "Welcome, Dear Pilgrim",
    welcomeSubtitle: "I'm your Hajj guide. Ask me about rituals, duas, or practical guidance.",
    quickQuestions: "Quick Questions",
    tawafSteps: "Tawaf Steps",
    hajjDuas: "Hajj Duas",
    ihramRules: "Ihram Rules",
    dayOfArafat: "Day of Arafat",
    askPlaceholder: "Ask about Hajj rituals...",
    consultScholar: "Consult a qualified scholar for religious rulings",
    newConversation: "New Conversation",
    yourLocation: "Your Location",
    nextStep: "Next Step",
    tips: "Tips",
    tryAgain: "Try Again",
    unableToLoadMap: "Unable to load map",
    liveMap: "Live Map",
    backToChat: "Back to Chat",
    hajjLocations: "Hajj Locations",
    familyGroup: "Family Group",
    create: "Create",
    join: "Join",
    yourName: "Your name",
    groupName: "Group name",
    inviteCode: "Invite code",
    cancel: "Cancel",
    members: "Members",
    you: "you",
    copied: "Copied!",
    inviteLinkCopied: "Invite link copied to clipboard",
    currentStatus: "Current Status",
    statusSafe: "You are Safe",
    statusAssistance: "Assistance Active",
    statusEmergency: "Emergency Being Managed",
    whatToDoNow: "What to do now",
    needHelp: "Need Help",
    helpConnecting: "Connecting...",
    helpConnected: "Connected",
    helpSpeakNow: "You can speak now",
    helpEndCall: "End Call",
    helpError: "Connection Error",
    helpTryAgain: "Please try again",
    emergency: "Emergency",
    emergencyConfirmTitle: "Confirm Emergency",
    emergencyConfirmDesc: "This will alert emergency services. Only use for real emergencies.",
    emergencyConfirm: "Yes, I Need Emergency Help",
    preparation: "Preparation",
    signIn: "Sign In",
    signOut: "Sign Out",
    noUpdateMeansNormal: "No update means everything is normal",
    familyStatus: "Family Status",
    lastUpdate: "Last update",
    preparationProgress: "Preparation Progress",
    stepComplete: "Complete",
    stepPending: "Pending",
    locationStaleWarning: "Location not updated — showing last known position",
    whatsNewSinceJuly1: "What's new since July 1",
    seeFullChangelog: "See full changelog",
  },
  ar: {
    hajjGuide: "دليل الحج",
    yourAIGuide: "مرشدك الذكي",
    bismillah: "بسم الله",
    assalamuAlaikum: "السلام عليكم",
    welcomePilgrim: "أهلاً بك أيها الحاج الكريم",
    welcomeSubtitle: "أنا مرشدك للحج. اسألني عن المناسك أو الأدعية أو أي إرشادات عملية.",
    quickQuestions: "أسئلة سريعة",
    tawafSteps: "خطوات الطواف",
    hajjDuas: "أدعية الحج",
    ihramRules: "محظورات الإحرام",
    dayOfArafat: "يوم عرفة",
    askPlaceholder: "اسأل عن مناسك الحج...",
    consultScholar: "للاستشارات الفقهية راجع عالماً متخصصاً",
    newConversation: "محادثة جديدة",
    yourLocation: "موقعك الحالي",
    nextStep: "الخطوة التالية",
    tips: "نصائح",
    tryAgain: "حاول مجدداً",
    unableToLoadMap: "تعذر تحميل الخريطة",
    liveMap: "الخريطة المباشرة",
    backToChat: "العودة للمحادثة",
    hajjLocations: "مواقع الحج",
    familyGroup: "مجموعة العائلة",
    create: "إنشاء",
    join: "انضمام",
    yourName: "اسمك",
    groupName: "اسم المجموعة",
    inviteCode: "رمز الدعوة",
    cancel: "إلغاء",
    members: "الأعضاء",
    you: "أنت",
    copied: "تم النسخ!",
    inviteLinkCopied: "تم نسخ رابط الدعوة",
    currentStatus: "الحالة الحالية",
    statusSafe: "أنت بأمان",
    statusAssistance: "المساعدة جارية",
    statusEmergency: "جاري التعامل مع الطوارئ",
    whatToDoNow: "ما يجب فعله الآن",
    needHelp: "أحتاج مساعدة",
    helpConnecting: "جاري الاتصال...",
    helpConnected: "تم الاتصال",
    helpSpeakNow: "يمكنك التحدث الآن",
    helpEndCall: "إنهاء المكالمة",
    helpError: "خطأ في الاتصال",
    helpTryAgain: "يرجى المحاولة مجدداً",
    emergency: "طوارئ",
    emergencyConfirmTitle: "تأكيد الطوارئ",
    emergencyConfirmDesc: "سيتم تنبيه خدمات الطوارئ. استخدم فقط للحالات الحقيقية.",
    emergencyConfirm: "نعم، أحتاج مساعدة طارئة",
    preparation: "التحضير",
    signIn: "تسجيل الدخول",
    signOut: "تسجيل الخروج",
    noUpdateMeansNormal: "عدم وجود تحديث يعني أن كل شيء طبيعي",
    familyStatus: "حالة العائلة",
    lastUpdate: "آخر تحديث",
    preparationProgress: "تقدم التحضير",
    stepComplete: "مكتمل",
    stepPending: "قيد الانتظار",
    locationStaleWarning: "الموقع لم يُحدَّث — يُعرض آخر موقع معروف",
    whatsNewSinceJuly1: "ما الجديد منذ ١ يوليو",
    seeFullChangelog: "اطلع على سجل التغييرات الكامل",
  },
  ur: {
    hajjGuide: "حج گائیڈ",
    yourAIGuide: "آپ کا AI گائیڈ",
    bismillah: "بسم اللہ",
    assalamuAlaikum: "السلام علیکم",
    welcomePilgrim: "خوش آمدید، عزیز حاجی",
    welcomeSubtitle: "میں آپ کا حج گائیڈ ہوں۔ مناسک، دعاؤں یا عملی رہنمائی کے بارے میں پوچھیں۔",
    quickQuestions: "فوری سوالات",
    tawafSteps: "طواف کے مراحل",
    hajjDuas: "حج کی دعائیں",
    ihramRules: "احرام کے قواعد",
    dayOfArafat: "یوم عرفہ",
    askPlaceholder: "حج کے مناسک کے بارے میں پوچھیں...",
    consultScholar: "مذہبی فیصلوں کے لیے کسی عالم سے رجوع کریں",
    newConversation: "نئی گفتگو",
    yourLocation: "آپ کا مقام",
    nextStep: "اگلا قدم",
    tips: "تجاویز",
    tryAgain: "دوبارہ کوشش کریں",
    unableToLoadMap: "نقشہ لوڈ نہیں ہو سکا",
    liveMap: "براہ راست نقشہ",
    backToChat: "چیٹ پر واپس",
    hajjLocations: "حج کے مقامات",
    familyGroup: "خاندانی گروپ",
    create: "بنائیں",
    join: "شامل ہوں",
    yourName: "آپ کا نام",
    groupName: "گروپ کا نام",
    inviteCode: "دعوتی کوڈ",
    cancel: "منسوخ",
    members: "ممبران",
    you: "آپ",
    copied: "کاپی ہوگیا!",
    inviteLinkCopied: "دعوتی لنک کاپی ہوگیا",
    currentStatus: "موجودہ حالت",
    statusSafe: "آپ محفوظ ہیں",
    statusAssistance: "مدد جاری ہے",
    statusEmergency: "ایمرجنسی کا انتظام ہو رہا ہے",
    whatToDoNow: "اب کیا کریں",
    needHelp: "مدد چاہیے",
    helpConnecting: "جڑ رہا ہے...",
    helpConnected: "جڑ گیا",
    helpSpeakNow: "اب بولیں",
    helpEndCall: "کال ختم کریں",
    helpError: "کنکشن میں خرابی",
    helpTryAgain: "دوبارہ کوشش کریں",
    emergency: "ایمرجنسی",
    emergencyConfirmTitle: "ایمرجنسی کی تصدیق",
    emergencyConfirmDesc: "ایمرجنسی سروسز کو الرٹ کیا جائے گا۔ صرف اصل ایمرجنسی کے لیے استعمال کریں۔",
    emergencyConfirm: "ہاں، مجھے فوری مدد چاہیے",
    preparation: "تیاری",
    signIn: "سائن ان",
    signOut: "سائن آؤٹ",
    noUpdateMeansNormal: "کوئی اپڈیٹ نہ ہونے کا مطلب سب ٹھیک ہے",
    familyStatus: "خاندان کی حالت",
    lastUpdate: "آخری اپڈیٹ",
    preparationProgress: "تیاری کی پیشرفت",
    stepComplete: "مکمل",
    stepPending: "زیر التواء",
    locationStaleWarning: "Location update نہیں ہوئی — پچھلی location دکھائی جا رہی ہے",
    whatsNewSinceJuly1: "۱ جولائی کے بعد کیا نیا ہے",
    seeFullChangelog: "مکمل changelog دیکھیں",
  },
  hi: {
    hajjGuide: "हज गाइड",
    yourAIGuide: "आपका AI गाइड",
    bismillah: "बिस्मिल्लाह",
    assalamuAlaikum: "अस्सलामु अलैकुम",
    welcomePilgrim: "स्वागत है, प्रिय हाजी",
    welcomeSubtitle: "मैं आपका हज गाइड हूं। रीति-रिवाजों, दुआओं या व्यावहारिक मार्गदर्शन के बारे में पूछें।",
    quickQuestions: "त्वरित प्रश्न",
    tawafSteps: "तवाफ के चरण",
    hajjDuas: "हज की दुआएं",
    ihramRules: "इहराम के नियम",
    dayOfArafat: "अरफात का दिन",
    askPlaceholder: "हज के रीति-रिवाजों के बारे में पूछें...",
    consultScholar: "धार्मिक निर्णयों के लिए किसी आलिम से परामर्श करें",
    newConversation: "नई बातचीत",
    yourLocation: "आपका स्थान",
    nextStep: "अगला कदम",
    tips: "सुझाव",
    tryAgain: "पुनः प्रयास करें",
    unableToLoadMap: "मानचित्र लोड नहीं हो सका",
    liveMap: "लाइव मानचित्र",
    backToChat: "चैट पर वापस",
    hajjLocations: "हज के स्थान",
    familyGroup: "पारिवारिक समूह",
    create: "बनाएं",
    join: "जुड़ें",
    yourName: "आपका नाम",
    groupName: "समूह का नाम",
    inviteCode: "आमंत्रण कोड",
    cancel: "रद्द करें",
    members: "सदस्य",
    you: "आप",
    copied: "कॉपी हो गया!",
    inviteLinkCopied: "आमंत्रण लिंक कॉपी हो गया",
    currentStatus: "वर्तमान स्थिति",
    statusSafe: "आप सुरक्षित हैं",
    statusAssistance: "सहायता सक्रिय",
    statusEmergency: "आपातकाल प्रबंधित हो रहा है",
    whatToDoNow: "अब क्या करें",
    needHelp: "मदद चाहिए",
    helpConnecting: "कनेक्ट हो रहा है...",
    helpConnected: "कनेक्ट हो गया",
    helpSpeakNow: "अब बोलें",
    helpEndCall: "कॉल समाप्त करें",
    helpError: "कनेक्शन त्रुटि",
    helpTryAgain: "कृपया पुनः प्रयास करें",
    emergency: "आपातकाल",
    emergencyConfirmTitle: "आपातकाल की पुष्टि करें",
    emergencyConfirmDesc: "आपातकालीन सेवाओं को सूचित किया जाएगा। केवल वास्तविक आपातकाल के लिए उपयोग करें।",
    emergencyConfirm: "हाँ, मुझे आपातकालीन मदद चाहिए",
    preparation: "तैयारी",
    signIn: "साइन इन",
    signOut: "साइन आउट",
    noUpdateMeansNormal: "कोई अपडेट न होने का मतलब सब ठीक है",
    familyStatus: "परिवार की स्थिति",
    lastUpdate: "अंतिम अपडेट",
    preparationProgress: "तैयारी की प्रगति",
    stepComplete: "पूर्ण",
    stepPending: "लंबित",
    locationStaleWarning: "Location update नहीं हुई — पिछली location दिखाई जा रही है",
    whatsNewSinceJuly1: "1 जुलाई के बाद क्या नया है",
    seeFullChangelog: "पूर्ण changelog देखें",
  },
  ta: {
    hajjGuide: "ஹஜ் வழிகாட்டி",
    yourAIGuide: "உங்கள் AI வழிகாட்டி",
    bismillah: "பிஸ்மில்லாஹ்",
    assalamuAlaikum: "அஸ்ஸலாமு அலைக்கும்",
    welcomePilgrim: "வரவேற்கிறோம், அன்பான ஹாஜி",
    welcomeSubtitle: "நான் உங்கள் ஹஜ் வழிகாட்டி. சடங்குகள், துஆக்கள் அல்லது நடைமுறை வழிகாட்டுதல் பற்றி கேளுங்கள்.",
    quickQuestions: "விரைவு கேள்விகள்",
    tawafSteps: "தவாஃப் படிகள்",
    hajjDuas: "ஹஜ் துஆக்கள்",
    ihramRules: "இஹ்ராம் விதிகள்",
    dayOfArafat: "அரஃபா நாள்",
    askPlaceholder: "ஹஜ் சடங்குகள் பற்றி கேளுங்கள்...",
    consultScholar: "மத தீர்ப்புகளுக்கு ஒரு அறிஞரை அணுகுங்கள்",
    newConversation: "புதிய உரையாடல்",
    yourLocation: "உங்கள் இடம்",
    nextStep: "அடுத்த படி",
    tips: "குறிப்புகள்",
    tryAgain: "மீண்டும் முயற்சிக்கவும்",
    unableToLoadMap: "வரைபடம் ஏற்ற முடியவில்லை",
    liveMap: "நேரடி வரைபடம்",
    backToChat: "அரட்டைக்கு திரும்பு",
    hajjLocations: "ஹஜ் இடங்கள்",
    familyGroup: "குடும்ப குழு",
    create: "உருவாக்கு",
    join: "சேர்",
    yourName: "உங்கள் பெயர்",
    groupName: "குழு பெயர்",
    inviteCode: "அழைப்பு குறியீடு",
    cancel: "ரத்து செய்",
    members: "உறுப்பினர்கள்",
    you: "நீங்கள்",
    copied: "நகலெடுக்கப்பட்டது!",
    inviteLinkCopied: "அழைப்பு இணைப்பு நகலெடுக்கப்பட்டது",
    currentStatus: "தற்போதைய நிலை",
    statusSafe: "நீங்கள் பாதுகாப்பாக உள்ளீர்கள்",
    statusAssistance: "உதவி செயலில்",
    statusEmergency: "அவசரநிலை நிர்வகிக்கப்படுகிறது",
    whatToDoNow: "இப்போது என்ன செய்ய வேண்டும்",
    needHelp: "உதவி தேவை",
    helpConnecting: "இணைக்கிறது...",
    helpConnected: "இணைக்கப்பட்டது",
    helpSpeakNow: "இப்போது பேசலாம்",
    helpEndCall: "அழைப்பை முடி",
    helpError: "இணைப்பு பிழை",
    helpTryAgain: "மீண்டும் முயற்சிக்கவும்",
    emergency: "அவசரநிலை",
    emergencyConfirmTitle: "அவசரநிலையை உறுதிப்படுத்தவும்",
    emergencyConfirmDesc: "அவசர சேவைகளுக்கு எச்சரிக்கை அனுப்பப்படும். உண்மையான அவசரநிலைக்கு மட்டும் பயன்படுத்தவும்.",
    emergencyConfirm: "ஆம், எனக்கு அவசர உதவி தேவை",
    preparation: "தயாரிப்பு",
    signIn: "உள்நுழை",
    signOut: "வெளியேறு",
    noUpdateMeansNormal: "புதுப்பிப்பு இல்லை என்றால் எல்லாம் சரி",
    familyStatus: "குடும்ப நிலை",
    lastUpdate: "கடைசி புதுப்பிப்பு",
    preparationProgress: "தயாரிப்பு முன்னேற்றம்",
    stepComplete: "முடிந்தது",
    stepPending: "நிலுவையில்",
    locationStaleWarning: "இடம் புதுப்பிக்கப்படவில்லை — கடைசியாக அறியப்பட்ட இடம் காட்டப்படுகிறது",
    whatsNewSinceJuly1: "ஜூலை 1 முதல் புதியது என்ன",
    seeFullChangelog: "முழு மாற்றப் பதிவையும் காண்க",
  },
  te: {
    hajjGuide: "హజ్ గైడ్",
    yourAIGuide: "మీ AI గైడ్",
    bismillah: "బిస్మిల్లాహ్",
    assalamuAlaikum: "అస్సలాము అలైకుమ్",
    welcomePilgrim: "స్వాగతం, ప్రియమైన హాజీ",
    welcomeSubtitle: "నేను మీ హజ్ గైడ్. ఆచారాలు, దుఆలు లేదా ఆచరణాత్మక మార్గదర్శకత్వం గురించి అడగండి.",
    quickQuestions: "త్వరిత ప్రశ్నలు",
    tawafSteps: "తవాఫ్ దశలు",
    hajjDuas: "హజ్ దుఆలు",
    ihramRules: "ఇహ్రామ్ నియమాలు",
    dayOfArafat: "అరఫా రోజు",
    askPlaceholder: "హజ్ ఆచారాల గురించి అడగండి...",
    consultScholar: "మత తీర్పుల కోసం ఒక పండితుడిని సంప్రదించండి",
    newConversation: "కొత్త సంభాషణ",
    yourLocation: "మీ స్థానం",
    nextStep: "తదుపరి దశ",
    tips: "చిట్కాలు",
    tryAgain: "మళ్ళీ ప్రయత్నించండి",
    unableToLoadMap: "మ్యాప్ లోడ్ కాలేదు",
    liveMap: "లైవ్ మ్యాప్",
    backToChat: "చాట్‌కు తిరిగి వెళ్ళు",
    hajjLocations: "హజ్ ప్రదేశాలు",
    familyGroup: "కుటుంబ సమూహం",
    create: "సృష్టించు",
    join: "చేరు",
    yourName: "మీ పేరు",
    groupName: "సమూహం పేరు",
    inviteCode: "ఆహ్వాన కోడ్",
    cancel: "రద్దు చేయి",
    members: "సభ్యులు",
    you: "మీరు",
    copied: "కాపీ చేయబడింది!",
    inviteLinkCopied: "ఆహ్వాన లింక్ కాపీ చేయబడింది",
    currentStatus: "ప్రస్తుత స్థితి",
    statusSafe: "మీరు సురక్షితంగా ఉన్నారు",
    statusAssistance: "సహాయం క్రియాశీలంగా ఉంది",
    statusEmergency: "అత్యవసర పరిస్థితి నిర్వహించబడుతోంది",
    whatToDoNow: "ఇప్పుడు ఏమి చేయాలి",
    needHelp: "సహాయం కావాలి",
    helpConnecting: "కనెక్ట్ అవుతోంది...",
    helpConnected: "కనెక్ట్ అయింది",
    helpSpeakNow: "ఇప్పుడు మాట్లాడవచ్చు",
    helpEndCall: "కాల్ ముగించు",
    helpError: "కనెక్షన్ లోపం",
    helpTryAgain: "దయచేసి మళ్ళీ ప్రయత్నించండి",
    emergency: "అత్యవసర పరిస్థితి",
    emergencyConfirmTitle: "అత్యవసర పరిస్థితిని నిర్ధారించండి",
    emergencyConfirmDesc: "అత్యవసర సేవలకు హెచ్చరిక పంపబడుతుంది. నిజమైన అత్యవసర పరిస్థితుల కోసం మాత్రమే ఉపయోగించండి.",
    emergencyConfirm: "అవును, నాకు అత్యవసర సహాయం కావాలి",
    preparation: "తయారీ",
    signIn: "సైన్ ఇన్",
    signOut: "సైన్ అవుట్",
    noUpdateMeansNormal: "అప్‌డేట్ లేకపోతే అంతా బాగానే ఉంది",
    familyStatus: "కుటుంబ స్థితి",
    lastUpdate: "చివరి అప్‌డేట్",
    preparationProgress: "తయారీ పురోగతి",
    stepComplete: "పూర్తయింది",
    stepPending: "పెండింగ్‌లో ఉంది",
    locationStaleWarning: "స్థానం అప్‌డేట్ కాలేదు — చివరిగా తెలిసిన స్థానం చూపబడుతోంది",
    whatsNewSinceJuly1: "జులై 1 నుండి కొత్తవి ఏమిటి",
    seeFullChangelog: "పూర్తి changelog చూడండి",
  },
  mr: {
    hajjGuide: "हज मार्गदर्शक",
    yourAIGuide: "तुमचा AI मार्गदर्शक",
    bismillah: "बिस्मिल्लाह",
    assalamuAlaikum: "अस्सलामु अलैकुम",
    welcomePilgrim: "स्वागत आहे, प्रिय हाजी",
    welcomeSubtitle: "मी तुमचा हज मार्गदर्शक आहे. विधी, दुआ किंवा व्यावहारिक मार्गदर्शनाबद्दल विचारा.",
    quickQuestions: "जलद प्रश्न",
    tawafSteps: "तवाफ पायऱ्या",
    hajjDuas: "हज दुआ",
    ihramRules: "इहराम नियम",
    dayOfArafat: "अरफाचा दिवस",
    askPlaceholder: "हज विधींबद्दल विचारा...",
    consultScholar: "धार्मिक निर्णयांसाठी एखाद्या आलिमाचा सल्ला घ्या",
    newConversation: "नवीन संभाषण",
    yourLocation: "तुमचे स्थान",
    nextStep: "पुढील पाऊल",
    tips: "टिप्स",
    tryAgain: "पुन्हा प्रयत्न करा",
    unableToLoadMap: "नकाशा लोड होऊ शकला नाही",
    liveMap: "लाइव्ह नकाशा",
    backToChat: "चॅटवर परत",
    hajjLocations: "हज ठिकाणे",
    familyGroup: "कुटुंब गट",
    create: "तयार करा",
    join: "सामील व्हा",
    yourName: "तुमचे नाव",
    groupName: "गटाचे नाव",
    inviteCode: "आमंत्रण कोड",
    cancel: "रद्द करा",
    members: "सदस्य",
    you: "तुम्ही",
    copied: "कॉपी झाले!",
    inviteLinkCopied: "आमंत्रण लिंक कॉपी झाली",
    currentStatus: "सध्याची स्थिती",
    statusSafe: "तुम्ही सुरक्षित आहात",
    statusAssistance: "मदत सक्रिय",
    statusEmergency: "आणीबाणी व्यवस्थापित होत आहे",
    whatToDoNow: "आता काय करावे",
    needHelp: "मदत हवी",
    helpConnecting: "जोडत आहे...",
    helpConnected: "जोडले गेले",
    helpSpeakNow: "आता बोला",
    helpEndCall: "कॉल संपवा",
    helpError: "कनेक्शन त्रुटी",
    helpTryAgain: "कृपया पुन्हा प्रयत्न करा",
    emergency: "आणीबाणी",
    emergencyConfirmTitle: "आणीबाणीची पुष्टी करा",
    emergencyConfirmDesc: "आणीबाणी सेवांना सूचित केले जाईल. फक्त खऱ्या आणीबाणीसाठी वापरा.",
    emergencyConfirm: "होय, मला आणीबाणी मदत हवी",
    preparation: "तयारी",
    signIn: "साइन इन",
    signOut: "साइन आउट",
    noUpdateMeansNormal: "अपडेट नाही म्हणजे सर्व ठीक आहे",
    familyStatus: "कुटुंबाची स्थिती",
    lastUpdate: "शेवटचे अपडेट",
    preparationProgress: "तयारी प्रगती",
    stepComplete: "पूर्ण",
    stepPending: "प्रलंबित",
    locationStaleWarning: "स्थान अपडेट झाले नाही — शेवटचे ठाऊक स्थान दाखवत आहे",
  },
  bn: {
    hajjGuide: "হজ গাইড",
    yourAIGuide: "আপনার AI গাইড",
    bismillah: "বিসমিল্লাহ",
    assalamuAlaikum: "আসসালামু আলাইকুম",
    welcomePilgrim: "স্বাগতম, প্রিয় হাজি",
    welcomeSubtitle: "আমি আপনার হজ গাইড। আচার-অনুষ্ঠান, দোয়া বা ব্যবহারিক নির্দেশনা সম্পর্কে জিজ্ঞাসা করুন।",
    quickQuestions: "দ্রুত প্রশ্ন",
    tawafSteps: "তাওয়াফ ধাপ",
    hajjDuas: "হজ দোয়া",
    ihramRules: "ইহরাম নিয়ম",
    dayOfArafat: "আরাফার দিন",
    askPlaceholder: "হজ আচার-অনুষ্ঠান সম্পর্কে জিজ্ঞাসা করুন...",
    consultScholar: "ধর্মীয় সিদ্ধান্তের জন্য একজন আলেমের সাথে পরামর্শ করুন",
    newConversation: "নতুন কথোপকথন",
    yourLocation: "আপনার অবস্থান",
    nextStep: "পরবর্তী ধাপ",
    tips: "টিপস",
    tryAgain: "আবার চেষ্টা করুন",
    unableToLoadMap: "মানচিত্র লোড করা যায়নি",
    liveMap: "লাইভ মানচিত্র",
    backToChat: "চ্যাটে ফিরে যান",
    hajjLocations: "হজ স্থান",
    familyGroup: "পারিবারিক গ্রুপ",
    create: "তৈরি করুন",
    join: "যোগ দিন",
    yourName: "আপনার নাম",
    groupName: "গ্রুপের নাম",
    inviteCode: "আমন্ত্রণ কোড",
    cancel: "বাতিল",
    members: "সদস্য",
    you: "আপনি",
    copied: "কপি হয়েছে!",
    inviteLinkCopied: "আমন্ত্রণ লিঙ্ক কপি হয়েছে",
    currentStatus: "বর্তমান অবস্থা",
    statusSafe: "আপনি নিরাপদ",
    statusAssistance: "সহায়তা সক্রিয়",
    statusEmergency: "জরুরি অবস্থা পরিচালিত হচ্ছে",
    whatToDoNow: "এখন কী করতে হবে",
    needHelp: "সাহায্য দরকার",
    helpConnecting: "সংযুক্ত হচ্ছে...",
    helpConnected: "সংযুক্ত হয়েছে",
    helpSpeakNow: "এখন কথা বলুন",
    helpEndCall: "কল শেষ করুন",
    helpError: "সংযোগ ত্রুটি",
    helpTryAgain: "অনুগ্রহ করে আবার চেষ্টা করুন",
    emergency: "জরুরি অবস্থা",
    emergencyConfirmTitle: "জরুরি অবস্থা নিশ্চিত করুন",
    emergencyConfirmDesc: "জরুরি সেবাগুলিকে সতর্ক করা হবে। শুধুমাত্র প্রকৃত জরুরি অবস্থার জন্য ব্যবহার করুন।",
    emergencyConfirm: "হ্যাঁ, আমার জরুরি সাহায্য দরকার",
    preparation: "প্রস্তুতি",
    signIn: "সাইন ইন",
    signOut: "সাইন আউট",
    noUpdateMeansNormal: "আপডেট নেই মানে সব ঠিক আছে",
    familyStatus: "পারিবারিক অবস্থা",
    lastUpdate: "সর্বশেষ আপডেট",
    preparationProgress: "প্রস্তুতি অগ্রগতি",
    stepComplete: "সম্পূর্ণ",
    stepPending: "বাকি আছে",
    locationStaleWarning: "অবস্থান আপডেট হয়নি — শেষ পরিচিত অবস্থান দেখানো হচ্ছে",
  },
  or: {
    hajjGuide: "ହଜ୍ଜ ଗାଇଡ୍",
    yourAIGuide: "ଆପଣଙ୍କ AI ଗାଇଡ୍",
    bismillah: "ବିସ୍ମିଲ୍ଲାହ",
    assalamuAlaikum: "ଆସ୍ସାଲାମୁ ଆଲାଇକୁମ",
    welcomePilgrim: "ସ୍ୱାଗତ, ପ୍ରିୟ ହାଜୀ",
    welcomeSubtitle: "ମୁଁ ଆପଣଙ୍କ ହଜ୍ଜ ଗାଇଡ୍। ରୀତି, ଦୁଆ ବା ବ୍ୟବହାରିକ ମାର୍ଗଦର୍ଶନ ବିଷୟରେ ପଚାରନ୍ତୁ।",
    quickQuestions: "ଦ୍ରୁତ ପ୍ରଶ୍ନ",
    tawafSteps: "ତାୱାଫ ପଦକ୍ଷେପ",
    hajjDuas: "ହଜ୍ଜ ଦୁଆ",
    ihramRules: "ଇହରାମ ନିୟମ",
    dayOfArafat: "ଆରଫା ଦିନ",
    askPlaceholder: "ହଜ୍ଜ ରୀତି ବିଷୟରେ ପଚାରନ୍ତୁ...",
    consultScholar: "ଧାର୍ମିକ ନିଷ୍ପତ୍ତି ପାଇଁ ଜଣେ ଆଲିମଙ୍କୁ ପରାମର୍ଶ କରନ୍ତୁ",
    newConversation: "ନୂତନ କଥାବାର୍ତ୍ତା",
    yourLocation: "ଆପଣଙ୍କ ଅବସ୍ଥାନ",
    nextStep: "ପରବର୍ତ୍ତୀ ପଦକ୍ଷେପ",
    tips: "ଟିପ୍ସ",
    tryAgain: "ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ",
    unableToLoadMap: "ମାନଚିତ୍ର ଲୋଡ୍ ହେଲା ନାହିଁ",
    liveMap: "ଲାଇଭ ମାନଚିତ୍ର",
    backToChat: "ଚାଟ୍ କୁ ଫେରନ୍ତୁ",
    hajjLocations: "ହଜ୍ଜ ସ୍ଥାନ",
    familyGroup: "ପରିବାର ଗୋଷ୍ଠୀ",
    create: "ତିଆରି କରନ୍ତୁ",
    join: "ଯୋଗ ଦିଅନ୍ତୁ",
    yourName: "ଆପଣଙ୍କ ନାମ",
    groupName: "ଗୋଷ୍ଠୀ ନାମ",
    inviteCode: "ନିମନ୍ତ୍ରଣ କୋଡ୍",
    cancel: "ବାତିଲ କରନ୍ତୁ",
    members: "ସଦସ୍ୟ",
    you: "ଆପଣ",
    copied: "କପି ହୋଇଗଲା!",
    inviteLinkCopied: "ନିମନ୍ତ୍ରଣ ଲିଙ୍କ କପି ହୋଇଗଲା",
    currentStatus: "ବର୍ତ୍ତମାନ ସ୍ଥିତି",
    statusSafe: "ଆପଣ ସୁରକ୍ଷିତ",
    statusAssistance: "ସହାୟତା ସକ୍ରିୟ",
    statusEmergency: "ଜରୁରୀକାଳୀନ ପରିସ୍ଥିତି ପରିଚାଳିତ ହେଉଛି",
    whatToDoNow: "ବର୍ତ୍ତମାନ କଣ କରିବେ",
    needHelp: "ସାହାଯ୍ୟ ଦରକାର",
    helpConnecting: "ସଂଯୋଗ ହେଉଛି...",
    helpConnected: "ସଂଯୋଗ ହୋଇଗଲା",
    helpSpeakNow: "ବର୍ତ୍ତମାନ କଥା କୁହନ୍ତୁ",
    helpEndCall: "କଲ ଶେଷ କରନ୍ତୁ",
    helpError: "ସଂଯୋଗ ତ୍ରୁଟି",
    helpTryAgain: "ଦୟାକରି ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ",
    emergency: "ଜରୁରୀକାଳୀନ ପରିସ୍ଥିତି",
    emergencyConfirmTitle: "ଜରୁରୀକାଳୀନ ପରିସ୍ଥିତି ନିଶ୍ଚିତ କରନ୍ତୁ",
    emergencyConfirmDesc: "ଜରୁରୀକାଳୀନ ସେବାକୁ ସତର୍କ କରାଯିବ। କେବଳ ପ୍ରକୃତ ଜରୁରୀକାଳୀନ ପରିସ୍ଥିତି ପାଇଁ ବ୍ୟବହାର କରନ୍ତୁ।",
    emergencyConfirm: "ହଁ, ମୋର ଜରୁରୀ ସାହାଯ୍ୟ ଦରକାର",
    preparation: "ପ୍ରସ୍ତୁତି",
    signIn: "ସାଇନ ଇନ",
    signOut: "ସାଇନ ଆଉଟ",
    noUpdateMeansNormal: "ଅପଡେଟ ନାହିଁ ମାନେ ସବୁ ଠିକ ଅଛି",
    familyStatus: "ପରିବାର ସ୍ଥିତି",
    lastUpdate: "ଶେଷ ଅପଡେଟ",
    preparationProgress: "ପ୍ରସ୍ତୁତି ଅଗ୍ରଗତି",
    stepComplete: "ସମ୍ପୂର୍ଣ୍ଣ",
    stepPending: "ବାକି ଅଛି",
    locationStaleWarning: "ସ୍ଥାନ ଅପଡେଟ୍ ହେଲା ନାହିଁ — ଶେଷ ଜଣାଥିବା ସ୍ଥାନ ଦେଖାଯାଉଛି",
  },
  ml: {
    hajjGuide: "ഹജ്ജ് ഗൈഡ്",
    yourAIGuide: "നിങ്ങളുടെ AI ഗൈഡ്",
    bismillah: "ബിസ്മില്ലാഹ്",
    assalamuAlaikum: "അസ്സലാമു അലൈക്കും",
    welcomePilgrim: "സ്വാഗതം, പ്രിയ ഹാജി",
    welcomeSubtitle: "ഞാൻ നിങ്ങളുടെ ഹജ്ജ് ഗൈഡ് ആണ്. ആചാരങ്ങൾ, ദുആകൾ അല്ലെങ്കിൽ പ്രായോഗിക മാർഗ്ഗനിർദ്ദേശങ്ങളെക്കുറിച്ച് ചോദിക്കൂ.",
    quickQuestions: "വേഗ ചോദ്യങ്ങൾ",
    tawafSteps: "ത്വവാഫ് ഘട്ടങ്ങൾ",
    hajjDuas: "ഹജ്ജ് ദുആകൾ",
    ihramRules: "ഇഹ്റാം നിയമങ്ങൾ",
    dayOfArafat: "അറഫ ദിനം",
    askPlaceholder: "ഹജ്ജ് ആചാരങ്ങളെക്കുറിച്ച് ചോദിക്കൂ...",
    consultScholar: "മത വിധികൾക്ക് ഒരു പണ്ഡിതനെ സമീപിക്കുക",
    newConversation: "പുതിയ സംഭാഷണം",
    yourLocation: "നിങ്ങളുടെ സ്ഥാനം",
    nextStep: "അടുത്ത ഘട്ടം",
    tips: "നുറുങ്ങുകൾ",
    tryAgain: "വീണ്ടും ശ്രമിക്കുക",
    unableToLoadMap: "മാപ്പ് ലോഡ് ചെയ്യാൻ കഴിഞ്ഞില്ല",
    liveMap: "ലൈവ് മാപ്പ്",
    backToChat: "ചാറ്റിലേക്ക് മടങ്ങുക",
    hajjLocations: "ഹജ്ജ് സ്ഥലങ്ങൾ",
    familyGroup: "കുടുംബ ഗ്രൂപ്പ്",
    create: "സൃഷ്ടിക്കുക",
    join: "ചേരുക",
    yourName: "നിങ്ങളുടെ പേര്",
    groupName: "ഗ്രൂപ്പ് പേര്",
    inviteCode: "ക്ഷണ കോഡ്",
    cancel: "റദ്ദാക്കുക",
    members: "അംഗങ്ങൾ",
    you: "നിങ്ങൾ",
    copied: "പകർത്തി!",
    inviteLinkCopied: "ക്ഷണ ലിങ്ക് പകർത്തി",
    currentStatus: "നിലവിലെ നില",
    statusSafe: "നിങ്ങൾ സുരക്ഷിതമാണ്",
    statusAssistance: "സഹായം സജീവം",
    statusEmergency: "അടിയന്തര സ്ഥിതി കൈകാര്യം ചെയ്യുന്നു",
    whatToDoNow: "ഇപ്പോൾ എന്ത് ചെയ്യണം",
    needHelp: "സഹായം വേണം",
    helpConnecting: "കണക്ട് ചെയ്യുന്നു...",
    helpConnected: "കണക്ട് ചെയ്തു",
    helpSpeakNow: "ഇപ്പോൾ സംസാരിക്കാം",
    helpEndCall: "കോൾ അവസാനിപ്പിക്കുക",
    helpError: "കണക്ഷൻ പിശക്",
    helpTryAgain: "ദയവായി വീണ്ടും ശ്രമിക്കുക",
    emergency: "അടിയന്തര സ്ഥിതി",
    emergencyConfirmTitle: "അടിയന്തര സ്ഥിതി സ്ഥിരീകരിക്കുക",
    emergencyConfirmDesc: "അടിയന്തര സേവനങ്ങളെ അറിയിക്കും. യഥാർത്ഥ അടിയന്തര സ്ഥിതികൾക്ക് മാത്രം ഉപയോഗിക്കുക.",
    emergencyConfirm: "അതെ, എനിക്ക് അടിയന്തര സഹായം വേണം",
    preparation: "തയ്യാറെടുപ്പ്",
    signIn: "സൈൻ ഇൻ",
    signOut: "സൈൻ ഔട്ട്",
    noUpdateMeansNormal: "അപ്‌ഡേറ്റ് ഇല്ലെങ്കിൽ എല്ലാം ശരി",
    familyStatus: "കുടുംബ നില",
    lastUpdate: "അവസാന അപ്‌ഡേറ്റ്",
    preparationProgress: "തയ്യാറെടുപ്പ് പുരോഗതി",
    stepComplete: "പൂർത്തിയായി",
    stepPending: "ബാക്കിയുണ്ട്",
    locationStaleWarning: "സ്ഥാനം അപ്‌ഡേറ്റ് ചെയ്തില്ല — അറിയാവുന്ന അവസാന സ്ഥാനം കാണിക്കുന്നു",
  },
  pa: {
    hajjGuide: "ਹੱਜ ਗਾਈਡ",
    yourAIGuide: "ਤੁਹਾਡਾ AI ਗਾਈਡ",
    bismillah: "ਬਿਸਮਿੱਲਾਹ",
    assalamuAlaikum: "ਅੱਸਲਾਮੁ ਅਲੈਕੁਮ",
    welcomePilgrim: "ਜੀ ਆਇਆਂ ਨੂੰ, ਪਿਆਰੇ ਹਾਜੀ",
    welcomeSubtitle: "ਮੈਂ ਤੁਹਾਡਾ ਹੱਜ ਗਾਈਡ ਹਾਂ। ਰੀਤਾਂ, ਦੁਆਵਾਂ ਜਾਂ ਅਮਲੀ ਮਾਰਗਦਰਸ਼ਨ ਬਾਰੇ ਪੁੱਛੋ।",
    quickQuestions: "ਤੁਰੰਤ ਸਵਾਲ",
    tawafSteps: "ਤਵਾਫ਼ ਕਦਮ",
    hajjDuas: "ਹੱਜ ਦੁਆਵਾਂ",
    ihramRules: "ਇਹਰਾਮ ਨਿਯਮ",
    dayOfArafat: "ਅਰਫ਼ਾ ਦਾ ਦਿਨ",
    askPlaceholder: "ਹੱਜ ਰੀਤਾਂ ਬਾਰੇ ਪੁੱਛੋ...",
    consultScholar: "ਧਾਰਮਿਕ ਫੈਸਲਿਆਂ ਲਈ ਕਿਸੇ ਆਲਿਮ ਨਾਲ ਸਲਾਹ ਕਰੋ",
    newConversation: "ਨਵੀਂ ਗੱਲਬਾਤ",
    yourLocation: "ਤੁਹਾਡੀ ਥਾਂ",
    nextStep: "ਅਗਲਾ ਕਦਮ",
    tips: "ਸੁਝਾਅ",
    tryAgain: "ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ",
    unableToLoadMap: "ਨਕਸ਼ਾ ਲੋਡ ਨਹੀਂ ਹੋ ਸਕਿਆ",
    liveMap: "ਲਾਈਵ ਨਕਸ਼ਾ",
    backToChat: "ਚੈਟ ਤੇ ਵਾਪਸ",
    hajjLocations: "ਹੱਜ ਥਾਵਾਂ",
    familyGroup: "ਪਰਿਵਾਰਕ ਗਰੁੱਪ",
    create: "ਬਣਾਓ",
    join: "ਸ਼ਾਮਲ ਹੋਵੋ",
    yourName: "ਤੁਹਾਡਾ ਨਾਮ",
    groupName: "ਗਰੁੱਪ ਦਾ ਨਾਮ",
    inviteCode: "ਸੱਦਾ ਕੋਡ",
    cancel: "ਰੱਦ ਕਰੋ",
    members: "ਮੈਂਬਰ",
    you: "ਤੁਸੀਂ",
    copied: "ਕਾਪੀ ਹੋ ਗਿਆ!",
    inviteLinkCopied: "ਸੱਦਾ ਲਿੰਕ ਕਾਪੀ ਹੋ ਗਿਆ",
    currentStatus: "ਮੌਜੂਦਾ ਸਥਿਤੀ",
    statusSafe: "ਤੁਸੀਂ ਸੁਰੱਖਿਅਤ ਹੋ",
    statusAssistance: "ਮਦਦ ਸਰਗਰਮ",
    statusEmergency: "ਐਮਰਜੈਂਸੀ ਸੰਭਾਲੀ ਜਾ ਰਹੀ ਹੈ",
    whatToDoNow: "ਹੁਣ ਕੀ ਕਰਨਾ ਹੈ",
    needHelp: "ਮਦਦ ਚਾਹੀਦੀ ਹੈ",
    helpConnecting: "ਜੁੜ ਰਿਹਾ ਹੈ...",
    helpConnected: "ਜੁੜ ਗਿਆ",
    helpSpeakNow: "ਹੁਣ ਬੋਲੋ",
    helpEndCall: "ਕਾਲ ਖਤਮ ਕਰੋ",
    helpError: "ਕੁਨੈਕਸ਼ਨ ਗਲਤੀ",
    helpTryAgain: "ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ",
    emergency: "ਐਮਰਜੈਂਸੀ",
    emergencyConfirmTitle: "ਐਮਰਜੈਂਸੀ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ",
    emergencyConfirmDesc: "ਐਮਰਜੈਂਸੀ ਸੇਵਾਵਾਂ ਨੂੰ ਸੂਚਿਤ ਕੀਤਾ ਜਾਵੇਗਾ। ਸਿਰਫ਼ ਅਸਲ ਐਮਰਜੈਂਸੀ ਲਈ ਵਰਤੋ।",
    emergencyConfirm: "ਹਾਂ, ਮੈਨੂੰ ਐਮਰਜੈਂਸੀ ਮਦਦ ਚਾਹੀਦੀ ਹੈ",
    preparation: "ਤਿਆਰੀ",
    signIn: "ਸਾਈਨ ਇਨ",
    signOut: "ਸਾਈਨ ਆਊਟ",
    noUpdateMeansNormal: "ਕੋਈ ਅਪਡੇਟ ਨਹੀਂ ਮਤਲਬ ਸਭ ਠੀਕ ਹੈ",
    familyStatus: "ਪਰਿਵਾਰ ਦੀ ਸਥਿਤੀ",
    lastUpdate: "ਆਖਰੀ ਅਪਡੇਟ",
    preparationProgress: "ਤਿਆਰੀ ਦੀ ਪ੍ਰਗਤੀ",
    stepComplete: "ਪੂਰਾ",
    stepPending: "ਬਾਕੀ",
    locationStaleWarning: "ਥਾਂ ਅਪਡੇਟ ਨਹੀਂ ਹੋਈ — ਆਖਰੀ ਜਾਣੀ ਪਛਾਣੀ ਥਾਂ ਵਿਖਾਈ ਜਾ ਰਹੀ ਹੈ",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey) => string;
  dir: "ltr" | "rtl";
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: TranslationKey) => translations[language][key] || translations.en[key];
  const currentLang = LANGUAGES.find(l => l.code === language)!;
  const dir = currentLang.dir;
  const isRTL = dir === "rtl";

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
