import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

const MAX_FILE_SIZE = 2 * 1024 * 1024; // 2MB
const ALLOWED_MIME_TYPES = [
  "application/pdf",
  "image/jpeg",
  "image/png",
  "image/gif",
  "image/webp",
];

// Application ID is now generated by the database using the sequence:
// UMR-YYYY-NNNNNN format (e.g., UMR-2026-000001)

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    // Rate limiting - prevent spam submissions
    const clientIp = req.headers.get('x-forwarded-for')?.split(',')[0]?.trim() || 
                     req.headers.get('x-real-ip') || 
                     'unknown';

    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseServiceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;

    // Call rate limit check function
    const rateLimitResponse = await fetch(
      `${supabaseUrl}/functions/v1/check-rate-limit`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${supabaseServiceKey}`,
        },
        body: JSON.stringify({
          action: 'free-umrah-apply',
          identifier: clientIp,
        }),
      }
    );

    const rateLimitResult = await rateLimitResponse.json();
    if (!rateLimitResult.allowed) {
      return new Response(
        JSON.stringify({ 
          error: 'Too many applications. Please try again later.',
          resetIn: rateLimitResult.resetIn 
        }),
        { status: 429, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }
    const contentType = req.headers.get("content-type") || "";
    
    let full_name: string;
    let age: number;
    let mobile: string;
    let state: string;
    let city: string;
    let pincode: string;
    let role: string;
    let masjid_name: string;
    let years_of_service: number;
    let never_umrah: boolean;
    let low_income: boolean;
    let social_harmony: boolean;
    let no_money_paid: boolean;
    let proof_type: string;
    let document: File | null = null;

    // Handle both FormData and JSON content types
    if (contentType.includes("multipart/form-data")) {
      const formData = await req.formData();
      full_name = formData.get("full_name") as string;
      age = parseInt(formData.get("age") as string) || 0;
      mobile = formData.get("mobile") as string;
      state = formData.get("state") as string;
      city = formData.get("city") as string;
      pincode = formData.get("pincode") as string;
      role = formData.get("role") as string;
      masjid_name = formData.get("masjid_name") as string;
      years_of_service = parseInt(formData.get("years_of_service") as string) || 0;
      never_umrah = formData.get("never_umrah") === "true";
      low_income = formData.get("low_income") === "true";
      social_harmony = formData.get("social_harmony") === "true";
      no_money_paid = formData.get("no_money_paid") === "true";
      proof_type = formData.get("proof_type") as string || "Masjid Certificate";
      document = formData.get("document") as File | null;
    } else {
      // Handle JSON body (fallback for testing or alternative clients)
      const body = await req.json();
      full_name = body.full_name;
      age = parseInt(body.age) || 0;
      mobile = body.mobile;
      state = body.state;
      city = body.city;
      pincode = body.pincode;
      role = body.role;
      masjid_name = body.masjid_name;
      years_of_service = parseInt(body.years_of_service) || 0;
      never_umrah = body.never_umrah === true || body.never_umrah === "true";
      low_income = body.low_income === true || body.low_income === "true";
      social_harmony = body.social_harmony === true || body.social_harmony === "true";
      no_money_paid = body.no_money_paid === true || body.no_money_paid === "true";
      proof_type = body.proof_type || "Masjid Certificate";
      // No document upload support via JSON
    }

    // Validate required fields
    if (!full_name || !mobile || !city || !state || !pincode || !role || !masjid_name) {
      return new Response(
        JSON.stringify({ error: "Missing required fields" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Validate mobile format (international: country code + number, 7-20 digits total)
    // Strip the + prefix if present for validation
    const cleanMobile = mobile.replace(/^\+/, '');
    if (!/^[0-9]{7,20}$/.test(cleanMobile)) {
      return new Response(
        JSON.stringify({ error: "Invalid mobile number format" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Validate pincode format (6 digits)
    if (!/^[0-9]{6}$/.test(pincode)) {
      return new Response(
        JSON.stringify({ error: "Invalid pincode format" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Validate age
    if (age < 18 || age > 100) {
      return new Response(
        JSON.stringify({ error: "Age must be between 18 and 100" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Validate role
    if (!["Imam", "Muazzin", "Hafiz"].includes(role)) {
      return new Response(
        JSON.stringify({ error: "Invalid role selected" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Validate declarations
    if (!never_umrah || !low_income || !social_harmony || !no_money_paid) {
      return new Response(
        JSON.stringify({ error: "All declarations must be accepted" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Initialize Supabase client with service role key (using variables from rate limit check)
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    // Check for duplicate application by mobile number
    const { data: existingApp } = await supabase
      .from("applicants")
      .select("application_id")
      .eq("mobile", mobile)
      .maybeSingle();

    if (existingApp) {
      return new Response(
        JSON.stringify({ 
          error: "Application already submitted with this mobile number",
          existingApplicationId: existingApp.application_id 
        }),
        { status: 409, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    let proofUrl: string | null = null;

    // Handle document upload if provided
    if (document) {
      // Check file size
      if (document.size > MAX_FILE_SIZE) {
        return new Response(
          JSON.stringify({ error: "File size must be under 2MB" }),
          { status: 413, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      // Check file type
      if (!ALLOWED_MIME_TYPES.includes(document.type)) {
        return new Response(
          JSON.stringify({ error: "Only PDF and image files allowed" }),
          { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      // Upload document to storage
      // Use a temporary ID for the file path until we get the generated application_id
      const tempId = `temp-${Date.now()}-${Math.random().toString(36).substring(2, 8)}`;
      const fileExt = document.name.split(".").pop();
      const filePath = `${tempId}/${Date.now()}.${fileExt}`;
      const fileBuffer = await document.arrayBuffer();

      const { error: uploadError } = await supabase.storage
        .from("proof-documents")
        .upload(filePath, fileBuffer, {
          contentType: document.type,
          upsert: false,
        });

      if (uploadError) {
        console.error("Upload error:", uploadError);
        return new Response(
          JSON.stringify({ error: "Failed to upload document" }),
          { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      proofUrl = filePath;
    }

    // Insert application into database - application_id is auto-generated by database
    const { data, error: insertError } = await supabase
      .from("applicants")
      .insert({
        full_name,
        age,
        mobile,
        state,
        city,
        pincode,
        role,
        masjid_name,
        years_of_service,
        never_umrah,
        low_income,
        social_harmony,
        no_money_paid,
        proof_type,
        proof_url: proofUrl,
        status: "SUBMITTED",
      })
      .select("application_id")
      .single();

    if (insertError) {
      console.error("Insert error:", insertError);
      return new Response(
        JSON.stringify({ error: "Failed to submit application" }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    return new Response(
      JSON.stringify({
        success: true,
        message: "Application submitted successfully",
        applicationId: data.application_id,
      }),
      { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );

  } catch (err) {
    console.error("Error:", err);
    const errorMessage = err instanceof Error ? err.message : "Server error";
    return new Response(
      JSON.stringify({ error: errorMessage }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
