import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

const MAX_FILE_SIZE = 2 * 1024 * 1024; // 2MB
const ALLOWED_MIME_TYPES = [
  "application/pdf",
  "image/jpeg",
  "image/png",
  "image/gif",
  "image/webp",
];

const IMAGE_ONLY_TYPES = [
  "image/jpeg",
  "image/png",
  "image/gif",
  "image/webp",
];

// Magic number validation to prevent MIME type spoofing
const validateFileSignature = (buffer: ArrayBuffer, claimedType: string): boolean => {
  const arr = new Uint8Array(buffer);
  if (arr.length < 4) return false;

  if (claimedType === "application/pdf") {
    return arr[0] === 0x25 && arr[1] === 0x50 && arr[2] === 0x44 && arr[3] === 0x46; // %PDF
  }
  if (claimedType === "image/jpeg") {
    return arr[0] === 0xFF && arr[1] === 0xD8 && arr[2] === 0xFF;
  }
  if (claimedType === "image/png") {
    return arr[0] === 0x89 && arr[1] === 0x50 && arr[2] === 0x4E && arr[3] === 0x47;
  }
  if (claimedType === "image/gif") {
    return arr[0] === 0x47 && arr[1] === 0x49 && arr[2] === 0x46 && arr[3] === 0x38; // GIF8
  }
  if (claimedType === "image/webp") {
    return arr.length >= 12 && arr[0] === 0x52 && arr[1] === 0x49 && arr[2] === 0x46 && arr[3] === 0x46
      && arr[8] === 0x57 && arr[9] === 0x45 && arr[10] === 0x42 && arr[11] === 0x50; // RIFF...WEBP
  }
  return false;
};

// Application ID is now generated by the database using the sequence:
// UMR-YYYY-NNNNNN format (e.g., UMR-2026-000001)

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseServiceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const contentType = req.headers.get("content-type") || "";
    
    let full_name: string;
    let age: number;
    let mobile: string;
    let state: string;
    let city: string;
    let pincode: string;
    let role: string;
    let masjid_name: string;
    let masjid_registration_number: string;
    let years_of_service: number;
    let never_umrah: boolean;
    let low_income: boolean;
    let social_harmony: boolean;
    let no_money_paid: boolean;
    let masjid_certificate: File | null = null;
    let passport_photo: File | null = null;

    // Handle both FormData and JSON content types
    if (contentType.includes("multipart/form-data")) {
      const formData = await req.formData();
      
      // Debug logging
      console.log("Form data entries:", Array.from(formData.entries()).map(([k, v]) => 
        `${k}=${v instanceof File ? `[File: ${v.name}]` : v}`
      ));
      
      full_name = formData.get("full_name") as string;
      age = parseInt(formData.get("age") as string) || 0;
      mobile = formData.get("mobile") as string;
      state = formData.get("state") as string;
      city = formData.get("city") as string;
      pincode = formData.get("pincode") as string;
      role = formData.get("role") as string;
      masjid_name = formData.get("masjid_name") as string;
      masjid_registration_number = formData.get("masjid_registration_number") as string;
      years_of_service = parseInt(formData.get("years_of_service") as string) || 0;
      never_umrah = formData.get("never_umrah") === "true";
      low_income = formData.get("low_income") === "true";
      social_harmony = formData.get("social_harmony") === "true";
      no_money_paid = formData.get("no_money_paid") === "true";
      masjid_certificate = formData.get("masjid_certificate") as File | null;
      passport_photo = formData.get("passport_photo") as File | null;
    } else {
      // Handle JSON body (fallback for testing or alternative clients)
      const body = await req.json();
      full_name = body.full_name;
      age = parseInt(body.age) || 0;
      mobile = body.mobile;
      state = body.state;
      city = body.city;
      pincode = body.pincode;
      role = body.role;
      masjid_name = body.masjid_name;
      masjid_registration_number = body.masjid_registration_number;
      years_of_service = parseInt(body.years_of_service) || 0;
      never_umrah = body.never_umrah === true || body.never_umrah === "true";
      low_income = body.low_income === true || body.low_income === "true";
      social_harmony = body.social_harmony === true || body.social_harmony === "true";
      no_money_paid = body.no_money_paid === true || body.no_money_paid === "true";
      // No document upload support via JSON
    }

    // Validate required fields
    const missingFields = [];
    if (!full_name) missingFields.push("full_name");
    if (!mobile) missingFields.push("mobile");
    if (!city) missingFields.push("city");
    if (!state) missingFields.push("state");
    if (!pincode) missingFields.push("pincode");
    if (!role) missingFields.push("role");
    if (!masjid_name) missingFields.push("masjid_name");
    if (!masjid_registration_number) missingFields.push("masjid_registration_number");
    
    if (missingFields.length > 0) {
      console.error("Missing fields:", missingFields);
      return new Response(
        JSON.stringify({ error: `Missing required fields: ${missingFields.join(", ")}` }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Validate mobile format (international: country code + number, 7-20 digits total)
    // Strip the + prefix if present for validation
    const cleanMobile = mobile.replace(/^\+/, '');
    if (!/^[0-9]{7,20}$/.test(cleanMobile)) {
      return new Response(
        JSON.stringify({ error: "Invalid mobile number format" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Rate limit by mobile number (strongest identifier - not spoofable like IP)
    const rateLimitResponse = await fetch(
      `${supabaseUrl}/functions/v1/check-rate-limit`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${supabaseServiceKey}`,
        },
        body: JSON.stringify({
          action: 'free-umrah-apply',
          identifier: `mobile:${cleanMobile}`,
        }),
      }
    );

    const rateLimitResult = await rateLimitResponse.json();
    if (!rateLimitResult.allowed) {
      return new Response(
        JSON.stringify({ 
          error: 'Too many applications. Please try again later.',
          resetIn: rateLimitResult.resetIn 
        }),
        { status: 429, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }
    // Validate pincode format (6 digits)
    if (!/^[0-9]{6}$/.test(pincode)) {
      return new Response(
        JSON.stringify({ error: "Invalid pincode format" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Validate age (18-60 years only)
    if (age < 18 || age > 60) {
      return new Response(
        JSON.stringify({ error: "Age must be between 18 and 60 years" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Validate role
    if (!["Imam", "Muazzin", "Hafiz"].includes(role)) {
      return new Response(
        JSON.stringify({ error: "Invalid role selected" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Validate declarations
    if (!never_umrah || !low_income || !social_harmony || !no_money_paid) {
      return new Response(
        JSON.stringify({ error: "All declarations must be accepted" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Validate both documents are provided
    if (!masjid_certificate || !passport_photo) {
      return new Response(
        JSON.stringify({ error: "Both Masjid Registration Certificate and Passport Photo are required" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Initialize Supabase client with service role key (using variables from rate limit check)
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    // Check for duplicate application by mobile number
    const { data: existingApp } = await supabase
      .from("applicants")
      .select("application_id")
      .eq("mobile", mobile)
      .maybeSingle();

    if (existingApp) {
      return new Response(
        JSON.stringify({ 
          error: "Application already submitted with this mobile number",
          existingApplicationId: existingApp.application_id 
        }),
        { status: 409, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    let masjidCertUrl: string | null = null;
    let passportPhotoUrl: string | null = null;

    // Handle Masjid Certificate upload
    if (masjid_certificate) {
      if (masjid_certificate.size > MAX_FILE_SIZE) {
        return new Response(
          JSON.stringify({ error: "Masjid Certificate file size must be under 2MB" }),
          { status: 413, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      if (!ALLOWED_MIME_TYPES.includes(masjid_certificate.type)) {
        return new Response(
          JSON.stringify({ error: "Masjid Certificate must be PDF or image file" }),
          { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      const tempId = `temp-${Date.now()}-${Math.random().toString(36).substring(2, 8)}`;
      const fileExt = masjid_certificate.name.split(".").pop();
      const filePath = `${tempId}/masjid-cert.${fileExt}`;
      const fileBuffer = await masjid_certificate.arrayBuffer();
      if (!validateFileSignature(fileBuffer, masjid_certificate.type)) {
        return new Response(
          JSON.stringify({ error: "Masjid Certificate file content does not match declared type" }),
          { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      const { error: certUploadError } = await supabase.storage
        .from("proof-documents")
        .upload(filePath, fileBuffer, {
          contentType: masjid_certificate.type,
          upsert: false,
        });
      if (certUploadError) {
        console.error("Masjid cert upload error:", certUploadError);
        return new Response(
          JSON.stringify({ error: "Failed to upload Masjid Certificate" }),
          { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      masjidCertUrl = filePath;
    }

    // Handle Passport Photo upload
    if (passport_photo) {
      if (passport_photo.size > MAX_FILE_SIZE) {
        return new Response(
          JSON.stringify({ error: "Passport Photo file size must be under 2MB" }),
          { status: 413, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      if (!IMAGE_ONLY_TYPES.includes(passport_photo.type)) {
        return new Response(
          JSON.stringify({ error: "Passport Photo must be an image file (JPEG, PNG, GIF, WebP)" }),
          { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      const tempId = `temp-${Date.now()}-${Math.random().toString(36).substring(2, 8)}`;
      const fileExt = passport_photo.name.split(".").pop();
      const filePath = `${tempId}/passport-photo.${fileExt}`;
      const fileBuffer = await passport_photo.arrayBuffer();
      if (!validateFileSignature(fileBuffer, passport_photo.type)) {
        return new Response(
          JSON.stringify({ error: "Passport Photo file content does not match declared type" }),
          { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      const { error: photoUploadError } = await supabase.storage
        .from("proof-documents")
        .upload(filePath, fileBuffer, {
          contentType: passport_photo.type,
          upsert: false,
        });
      if (photoUploadError) {
        console.error("Passport photo upload error:", photoUploadError);
        return new Response(
          JSON.stringify({ error: "Failed to upload Passport Photo" }),
          { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      passportPhotoUrl = filePath;
    }

    // Insert application into database - application_id is auto-generated by database
    const { data, error: insertError } = await supabase
      .from("applicants")
      .insert({
        full_name,
        age,
        mobile,
        state,
        city,
        pincode,
        role,
        masjid_name,
        masjid_registration_number,
        years_of_service,
        never_umrah,
        low_income,
        social_harmony,
        no_money_paid,
        proof_type: "Masjid Certificate + Passport Photo",
        proof_url: masjidCertUrl ? `${masjidCertUrl}|${passportPhotoUrl}` : null,
        status: "SUBMITTED",
      })
      .select("application_id")
      .single();

    if (insertError) {
      console.error("Insert error:", insertError);
      return new Response(
        JSON.stringify({ error: "Failed to submit application" }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    return new Response(
      JSON.stringify({
        success: true,
        message: "Application submitted successfully",
        applicationId: data.application_id,
      }),
      { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );

  } catch (err) {
    console.error("Error:", err);
    const errorMessage = err instanceof Error ? err.message : "Server error";
    return new Response(
      JSON.stringify({ error: errorMessage }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
