import { useMemo, useState } from "react";
import { MainLayout } from "@/components/MainLayout";
import { SEO } from "@/components/SEO";
import { useLanguage } from "@/contexts/LanguageContext";
import { useCirculars } from "@/hooks/useCirculars";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Progress } from "@/components/ui/progress";
import { Badge } from "@/components/ui/badge";
import { AlertTriangle, Download, FileCheck2, HeartPulse, Luggage, PlaneTakeoff, Printer, Search, ShieldCheck, WalletCards } from "lucide-react";

type Section = { id: string; title: string; icon: typeof FileCheck2; items: string[]; note?: string };
const sections: Section[] = [
  { id: "documents", title: "Required Documents", icon: FileCheck2, items: ["Original passport (minimum 6 months validity)", "Hajj visa", "Flight tickets", "Haj Committee confirmation letter", "Hotel and accommodation details", "Vaccination certificate (as per current Saudi regulations)", "Passport-size photographs", "Aadhaar card", "PAN card (optional)", "Emergency contact list", "Health insurance (if applicable)", "Medical prescriptions", "Blood group information", "Digital copies of all documents"] },
  { id: "clothing", title: "Packing Checklist — Clothing", icon: Luggage, items: ["Ihram (men)", "Abayas (women)", "Comfortable cotton clothes", "Undergarments", "Slippers or sandals", "Walking shoes", "Belt or pouch", "Socks", "Umbrella", "Sunglasses"] },
  { id: "care", title: "Packing Checklist — Personal Care", icon: Luggage, items: ["Unscented soap", "Unscented shampoo", "Toothbrush and toothpaste", "Towel", "Nail cutter (use before Ihram only)", "Tissue papers", "Wet wipes", "Hand sanitizer", "Face mask"] },
  { id: "medicines", title: "Medicines & Health Kit", icon: HeartPulse, items: ["Personal prescription medicines", "ORS", "Paracetamol", "Pain relief spray", "Bandages", "Antiseptic cream", "Thermometer", "Blood pressure medicine", "Diabetes medicine"] },
  { id: "electronics", title: "Electronics", icon: Luggage, items: ["Mobile phone", "Charger", "Power bank (airline compliant)", "Universal travel adapter", "Smart watch (if issued)", "Earphones"] },
  { id: "prohibited", title: "Items Not Allowed / Prohibited", icon: AlertTriangle, items: ["Sharp objects", "Explosives or firearms", "Illegal drugs", "Alcohol", "Pork products", "Highly flammable materials", "Counterfeit currency", "Drones (unless officially permitted)", "Any item prohibited under Saudi Customs regulations"], note: "Always check the latest airline, Saudi Customs, and official Hajj advisories before packing." },
  { id: "currency", title: "Currency & Payments", icon: WalletCards, items: ["Saudi Riyal", "International debit or credit cards", "Emergency cash", "Currency exchange plan", "Keep payment cards and cash secure"], note: "UPI acceptance is not guaranteed in Saudi Arabia. Carry an appropriate payment backup." },
  { id: "airport", title: "Airport Departure Checklist", icon: PlaneTakeoff, items: ["Reach the airport 4 hours before departure", "Carry all original documents", "Complete baggage tagging", "Complete immigration", "Complete security check", "Verify boarding gate"] },
  { id: "health", title: "Health Preparation", icon: HeartPulse, items: ["Check required vaccinations", "Hydration plan", "Walking practice", "Doctor consultation", "Emergency medical information card"] },
];
const storeKey = "hajcare-travel-preparation-v1";

export default function TravelPreparationGuidePage() {
  const { language, isRTL } = useLanguage(); const { circulars } = useCirculars();
  const [query, setQuery] = useState(""); const [done, setDone] = useState<Record<string, boolean>>(() => { try { return JSON.parse(localStorage.getItem(storeKey) || "{}"); } catch { return {}; } });
  const allItems = sections.flatMap((section) => section.items.map((item) => ({ id: `${section.id}:${item}`, item, section })));
  const visible = useMemo(() => sections.map((section) => ({ ...section, items: section.items.filter((item) => item.toLowerCase().includes(query.toLowerCase())) })).filter((section) => section.items.length > 0), [query]);
  const progress = allItems.length ? Math.round((allItems.filter(({ id }) => done[id]).length / allItems.length) * 100) : 0;
  const toggle = (id: string) => setDone((current) => { const next = { ...current, [id]: !current[id] }; localStorage.setItem(storeKey, JSON.stringify(next)); return next; });
  const print = () => window.print();
  const download = (name: string, values: string[]) => { const blob = new Blob([`${name}\n\n${values.map((item) => `☐ ${item}`).join("\n")}`], { type: "text/plain;charset=utf-8" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `${name.toLowerCase().replace(/[^a-z0-9]+/g, "-")}.txt`; link.click(); URL.revokeObjectURL(url); };
  const title = language === "hi" ? "प्री-हज इंडिया – यात्रा तैयारी और पैकिंग गाइड" : language === "ur" ? "پری حج انڈیا – سفری تیاری اور پیکنگ گائیڈ" : "Pre-Hajj India – Travel Preparation & Packing Guide";
  const updates = circulars.filter((c) => ["health", "travel", "visa"].includes(c.category) || /passport|visa|flight|health|vaccination|customs|travel/i.test(c.title)).slice(0, 4);
  return <MainLayout><SEO title="Travel Preparation & Packing Guide | Haj 2027" description="Documents, packing, prohibited items, health and airport preparation for Indian Hajj pilgrims." path="/pre-hajj-india/travel-preparation" type="article" />
    <main className="mx-auto max-w-4xl space-y-5 px-4 pb-24" dir={isRTL ? "rtl" : "ltr"}><header className="rounded-3xl border border-primary/15 bg-gradient-to-br from-primary/10 via-background to-amber-100/30 p-5 sm:p-8"><div className="flex items-start gap-3"><span className="rounded-2xl bg-primary p-3 text-primary-foreground"><Luggage className="h-7 w-7" /></span><div><h1 className="text-2xl font-bold sm:text-3xl">{title}</h1><p className="mt-2 text-muted-foreground">Prepare confidently for your sacred journey with complete travel guidance, required documents, packing checklist, prohibited items, and official travel requirements.</p></div></div><div className="mt-5"><div className="mb-2 flex justify-between text-sm font-medium"><span>Preparation progress</span><span>{progress}%</span></div><Progress value={progress} className="h-3" /></div><div className="mt-4 flex flex-wrap gap-2"><Button onClick={print}><Printer className="mr-2 h-4 w-4" />Print / Save as PDF</Button><Button variant="outline" onClick={() => download("Hajj packing checklist", sections.filter((s) => ["clothing", "care", "medicines", "electronics"].includes(s.id)).flatMap((s) => s.items))}><Download className="mr-2 h-4 w-4" />Download packing list</Button><Button variant="outline" onClick={() => download("Hajj document checklist", sections.find((s) => s.id === "documents")!.items)}><Download className="mr-2 h-4 w-4" />Documents</Button></div></header>
      <div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" /><Input className="pl-9" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search any item, document, medicine or airport step" /></div>
      <Accordion type="multiple" defaultValue={["documents", "clothing", "airport"]} className="space-y-3">{visible.map((section) => { const Icon = section.icon; return <AccordionItem key={section.id} value={section.id} className="rounded-2xl border bg-card px-4"><AccordionTrigger className="py-4 hover:no-underline"><span className="flex items-center gap-3 text-left"><span className="rounded-xl bg-primary/10 p-2 text-primary"><Icon className="h-5 w-5" /></span>{section.title}</span></AccordionTrigger><AccordionContent><div className="space-y-2 pb-4">{section.items.map((item) => { const id = `${section.id}:${item}`; return <label key={id} className="flex cursor-pointer items-center gap-3 rounded-xl px-2 py-2 hover:bg-muted/60"><Checkbox checked={Boolean(done[id])} onCheckedChange={() => toggle(id)} /><span className={done[id] ? "text-muted-foreground line-through" : ""}>{item}</span></label>; })}{section.note && <p className="mt-3 rounded-xl bg-amber-50 p-3 text-sm text-amber-900 dark:bg-amber-950/30 dark:text-amber-200">{section.note}</p>}</div></AccordionContent></AccordionItem>; })}</Accordion>
      <Card className="border-primary/20"><CardContent className="p-5"><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-primary" /><h2 className="font-bold">Important Official Guidelines</h2></div><p className="mt-1 text-sm text-muted-foreground">Latest verified travel, visa and health advisories from HajCare AI’s Official Updates centre.</p><div className="mt-4 space-y-2">{updates.length ? updates.map((update) => <a key={update.id} href="/circulars" className="block rounded-xl border p-3 transition hover:border-primary/40"><div className="flex gap-2"><Badge variant="outline">{update.source_name_display || update.source}</Badge><span className="font-medium">{update.title}</span></div><p className="mt-1 text-sm text-muted-foreground">{update.summary_en || "Read the verified official circular for full requirements."}</p></a>) : <p className="rounded-xl bg-muted p-3 text-sm text-muted-foreground">No matching verified advisory is published yet. Check Official Updates before travel.</p>}</div></CardContent></Card>
      <Card><CardContent className="p-5"><h2 className="font-bold">Download Centre</h2><p className="mt-1 text-sm text-muted-foreground">Save lists on your phone for offline access. For PDF, use Print / Save as PDF in your browser.</p><div className="mt-3 flex flex-wrap gap-2"><Button variant="outline" onClick={() => download("Emergency contacts reminder", ["Indian Haj Mission emergency contact", "Your group leader", "Family emergency contact", "Local emergency service"])}>Emergency contacts</Button><Button variant="outline" onClick={() => download("Airport guide", sections.find((s) => s.id === "airport")!.items)}>Airport guide</Button></div></CardContent></Card>
    </main></MainLayout>;
}
