import {
  Plane,
  Landmark,
  Building,
  MapPin,
  Moon,
  HandHeart,
  Bot,
  Users,
  HeartPulse,
  ScrollText,
  Phone,
  Route,
  LucideIcon,
} from "lucide-react";

export interface MenuItem {
  id: string;
  icon: LucideIcon;
  label: Record<string, string>;
  route: string;
  colorClass: string;
  priority?: boolean; // For sacred gold treatment
}

export interface MenuSection {
  id: string;
  title: Record<string, string>;
  items: MenuItem[];
}

// Simplified to 12 core items in 2 sections for elderly-friendly UX
export const menuSections: MenuSection[] = [
  // SECTION 1 – SACRED JOURNEY (Priority items with gold treatment)
  {
    id: "sacred-journey",
    title: {
      en: "Your Sacred Journey",
      ar: "رحلتك المقدسة",
      ur: "آپ کا مقدس سفر",
      hi: "आपकी पवित्र यात्रा",
      ta: "உங்கள் புனித பயணம்",
      te: "మీ పవిత్ర ప్రయాణం",
      mr: "तुमचा पवित्र प्रवास",
      bn: "আপনার পবিত্র যাত্রা",
      or: "ଆପଣଙ୍କ ପବିତ୍ର ଯାତ୍ରା",
      ml: "നിങ്ങളുടെ പുണ്യ യാത്ര",
      pa: "ਤੁਹਾਡੀ ਪਵਿੱਤਰ ਯਾਤਰਾ",
    },
    items: [
      {
        id: "hajj",
        icon: Landmark,
        label: {
          en: "Hajj Guide",
          ar: "دليل الحج",
          ur: "حج گائیڈ",
          hi: "हज गाइड",
          ta: "ஹஜ் வழிகாட்டி",
          te: "హజ్ గైడ్",
          mr: "हज मार्गदर्शक",
          bn: "হজ গাইড",
          or: "ହଜ ଗାଇଡ୍",
          ml: "ഹജ്ജ് ഗൈഡ്",
          pa: "ਹੱਜ ਗਾਈਡ",
        },
        route: "/prepare",
        colorClass: "icon-gold",
        priority: true,
      },
      {
        id: "umrah",
        icon: Moon,
        label: {
          en: "Umrah Guide",
          ar: "دليل العمرة",
          ur: "عمرہ گائیڈ",
          hi: "उमराह गाइड",
          ta: "உம்ரா வழிகாட்டி",
          te: "ఉమ్రా గైడ్",
          mr: "उमराह मार्गदर्शक",
          bn: "উমরাহ গাইড",
          or: "ଉମରାହ ଗାଇଡ୍",
          ml: "ഉംറ ഗൈഡ്",
          pa: "ਉਮਰਾਹ ਗਾਈਡ",
        },
        route: "/umrah",
        colorClass: "icon-gold",
        priority: true,
      },
      {
        id: "makkah",
        icon: Building,
        label: {
          en: "Makkah",
          ar: "مكة",
          ur: "مکہ",
          hi: "मक्का",
          ta: "மக்கா",
          te: "మక్కా",
          mr: "मक्का",
          bn: "মক্কা",
          or: "ମକ୍କା",
          ml: "മക്ക",
          pa: "ਮੱਕਾ",
        },
        route: "/makkah-guide",
        colorClass: "icon-gold",
        priority: true,
      },
      {
        id: "madinah",
        icon: MapPin,
        label: {
          en: "Madinah",
          ar: "المدينة",
          ur: "مدینہ",
          hi: "मदीना",
          ta: "மதீனா",
          te: "మదీనా",
          mr: "मदीना",
          bn: "মদিনা",
          or: "ମଦୀନା",
          ml: "മദീന",
          pa: "ਮਦੀਨਾ",
        },
        route: "/madinah-guide",
        colorClass: "icon-gold",
        priority: true,
      },
      {
        id: "dua",
        icon: HandHeart,
        label: {
          en: "Duas",
          ar: "الدعاء",
          ur: "دعائیں",
          hi: "दुआएं",
          ta: "துஆக்கள்",
          te: "దుఆలు",
          mr: "दुआ",
          bn: "দোয়া",
          or: "ଦୁଆ",
          ml: "ദുആകൾ",
          pa: "ਦੁਆਵਾਂ",
        },
        route: "/dua",
        colorClass: "icon-gold",
        priority: true,
      },
      {
        id: "assistant",
        icon: Bot,
        label: {
          en: "AI Help",
          ar: "المساعد",
          ur: "AI مدد",
          hi: "AI मदद",
          ta: "AI உதவி",
          te: "AI సహాయం",
          mr: "AI मदत",
          bn: "AI সাহায্য",
          or: "AI ସାହାଯ୍ୟ",
          ml: "AI സഹായം",
          pa: "AI ਮਦਦ",
        },
        route: "/chat",
        colorClass: "icon-teal",
      },
    ],
  },
  // SECTION 2 – ESSENTIALS
  {
    id: "essentials",
    title: {
      en: "Essentials",
      ar: "الأساسيات",
      ur: "ضروریات",
      hi: "आवश्यक",
      ta: "அத்தியாவசியம்",
      te: "అవసరాలు",
      mr: "आवश्यक",
      bn: "প্রয়োজনীয়",
      or: "ଆବଶ୍ୟକ",
      ml: "അത്യാവശ്യങ്ങൾ",
      pa: "ਜ਼ਰੂਰੀ",
    },
    items: [
      {
        id: "pre-hajj",
        icon: Plane,
        label: {
          en: "Before You Go",
          ar: "قبل السفر",
          ur: "جانے سے پہلے",
          hi: "जाने से पहले",
          ta: "செல்வதற்கு முன்",
          te: "వెళ్ళే ముందు",
          mr: "जाण्यापूर्वी",
          bn: "যাওয়ার আগে",
          or: "ଯିବା ପୂର୍ବରୁ",
          ml: "പോകുന്നതിന് മുമ്പ്",
          pa: "ਜਾਣ ਤੋਂ ਪਹਿਲਾਂ",
        },
        route: "/pre-hajj-india",
        colorClass: "icon-teal",
      },
      {
        id: "rules",
        icon: ScrollText,
        label: {
          en: "Rules",
          ar: "القواعد",
          ur: "قواعد",
          hi: "नियम",
          ta: "விதிகள்",
          te: "నియమాలు",
          mr: "नियम",
          bn: "নিয়ম",
          or: "ନିୟମ",
          ml: "നിയമങ്ങൾ",
          pa: "ਨਿਯਮ",
        },
        route: "/rules",
        colorClass: "icon-sand",
      },
      {
        id: "health",
        icon: HeartPulse,
        label: {
          en: "Health",
          ar: "الصحة",
          ur: "صحت",
          hi: "स्वास्थ्य",
          ta: "உடல்நலம்",
          te: "ఆరోగ్యం",
          mr: "आरोग्य",
          bn: "স্বাস্থ্য",
          or: "ସ୍ୱାସ୍ଥ୍ୟ",
          ml: "ആരോഗ്യം",
          pa: "ਸਿਹਤ",
        },
        route: "/health",
        colorClass: "icon-coral",
      },
      {
        id: "family-tracking",
        icon: Users,
        label: {
          en: "Family",
          ar: "العائلة",
          ur: "خاندان",
          hi: "परिवार",
          ta: "குடும்பம்",
          te: "కుటుంబం",
          mr: "कुटुंब",
          bn: "পরিবার",
          or: "ପରିବାର",
          ml: "കുടുംബം",
          pa: "ਪਰਿਵਾਰ",
        },
        route: "/family",
        colorClass: "icon-sky",
      },
      {
        id: "hajj-progress",
        icon: Route,
        label: {
          en: "Progress",
          ar: "التقدم",
          ur: "پیشرفت",
          hi: "प्रगति",
          ta: "முன்னேற்றம்",
          te: "పురోగతి",
          mr: "प्रगती",
          bn: "অগ্রগতি",
          or: "ପ୍ରଗତି",
          ml: "പുരോഗതി",
          pa: "ਪ੍ਰਗਤੀ",
        },
        route: "/hajj-progress",
        colorClass: "icon-emerald",
      },
      {
        id: "contacts",
        icon: Phone,
        label: {
          en: "Help",
          ar: "مساعدة",
          ur: "مدد",
          hi: "मदद",
          ta: "உதவி",
          te: "సహాయం",
          mr: "मदत",
          bn: "সাহায্য",
          or: "ସାହାଯ୍ୟ",
          ml: "സഹായം",
          pa: "ਮਦਦ",
        },
        route: "/contacts",
        colorClass: "icon-coral",
      },
    ],
  },
];
