import {
  Plane,
  ClipboardList,
  ScrollText,
  HeartPulse,
  Banknote,
  Wifi,
  Map,
  GraduationCap,
  Bot,
  Building,
  MapPin,
  Moon,
  Landmark,
  Sword,
  ShieldCheck,
  HandHeart,
  Flower2,
  HeartHandshake,
  UtensilsCrossed,
  Users,
  MessageCircle,
  Video,
  AlertTriangle,
  Stethoscope,
  Phone,
  Star,
  Gift,
  Headphones,
  Route,
  CreditCard,
  Wallet,
  LucideIcon,
} from "lucide-react";

export interface MenuItem {
  id: string;
  icon: LucideIcon;
  label: Record<string, string>;
  route: string;
  colorClass: string;
}

export interface MenuSection {
  id: string;
  title: Record<string, string>;
  items: MenuItem[];
}

// Spiritual, calm color classes using design system tokens
export const menuSections: MenuSection[] = [
  // SECTION A – BEFORE HAJJ
  {
    id: "before-hajj",
    title: {
      en: "Before Hajj",
      ar: "قبل الحج",
      ur: "حج سے پہلے",
      hi: "हज से पहले",
      ta: "ஹஜ்ஜுக்கு முன்",
      te: "హజ్ కు ముందు",
      mr: "हज आधी",
      bn: "হজের আগে",
      or: "ହଜ ପୂର୍ବରୁ",
      ml: "ഹജ്ജിന് മുമ്പ്",
      pa: "ਹੱਜ ਤੋਂ ਪਹਿਲਾਂ",
    },
    items: [
      {
        id: "pre-hajj",
        icon: Plane,
        label: {
          en: "Pre-Hajj India",
          ar: "قبل الحج الهند",
          ur: "حج سے پہلے انڈیا",
          hi: "प्री-हज इंडिया",
          ta: "முன் ஹஜ் இந்தியா",
          te: "ప్రీ-హజ్ ఇండియా",
          mr: "प्री-हज इंडिया",
          bn: "প্রি-হজ ভারত",
          or: "ପ୍ରି-ହଜ ଭାରତ",
          ml: "പ്രീ-ഹജ്ജ് ഇന്ത്യ",
          pa: "ਪ੍ਰੀ-ਹੱਜ ਇੰਡੀਆ",
        },
        route: "/pre-hajj-india",
        colorClass: "icon-teal",
      },
      {
        id: "preparation",
        icon: ClipboardList,
        label: {
          en: "Preparation",
          ar: "التحضير",
          ur: "تیاری",
          hi: "तैयारी",
          ta: "தயாரிப்பு",
          te: "తయారీ",
          mr: "तयारी",
          bn: "প্রস্তুতি",
          or: "ପ୍ରସ୍ତୁତି",
          ml: "തയ്യാറെടുപ്പ്",
          pa: "ਤਿਆਰੀ",
        },
        route: "/preparation",
        colorClass: "icon-sage",
      },
      {
        id: "rules",
        icon: ScrollText,
        label: {
          en: "Rules",
          ar: "القواعد",
          ur: "قواعد",
          hi: "नियम",
          ta: "விதிகள்",
          te: "నియమాలు",
          mr: "नियम",
          bn: "নিয়ম",
          or: "ନିୟମ",
          ml: "നിയമങ്ങൾ",
          pa: "ਨਿਯਮ",
        },
        route: "/rules",
        colorClass: "icon-sand",
      },
      {
        id: "health",
        icon: HeartPulse,
        label: {
          en: "Health",
          ar: "الصحة",
          ur: "صحت",
          hi: "स्वास्थ्य",
          ta: "உடல்நலம்",
          te: "ఆరోగ్యం",
          mr: "आरोग्य",
          bn: "স্বাস্থ্য",
          or: "ସ୍ୱାସ୍ଥ୍ୟ",
          ml: "ആരോഗ്യം",
          pa: "ਸਿਹਤ",
        },
        route: "/health",
        colorClass: "icon-coral",
      },
      {
        id: "money",
        icon: Banknote,
        label: {
          en: "Money",
          ar: "المال",
          ur: "پیسہ",
          hi: "पैसा",
          ta: "பணம்",
          te: "డబ్బు",
          mr: "पैसे",
          bn: "টাকা",
          or: "ପଇସା",
          ml: "പണം",
          pa: "ਪੈਸਾ",
        },
        route: "/money",
        colorClass: "icon-gold",
      },
      {
        id: "telecom",
        icon: Wifi,
        label: {
          en: "Telecom",
          ar: "اتصالات",
          ur: "ٹیلی کام",
          hi: "टेलीकॉम",
          ta: "டெலிகாம்",
          te: "టెలికాం",
          mr: "टेलिकॉम",
          bn: "টেলিকম",
          or: "ଟେଲିକମ",
          ml: "ടെലികോം",
          pa: "ਟੈਲੀਕਾਮ",
        },
        route: "/telecom",
        colorClass: "icon-sky",
      },
      {
        id: "map",
        icon: Map,
        label: {
          en: "Maps",
          ar: "الخرائط",
          ur: "نقشے",
          hi: "नक्शे",
          ta: "வரைபடங்கள்",
          te: "మ్యాప్‌లు",
          mr: "नकाशे",
          bn: "মানচিত্র",
          or: "ମାନଚିତ୍ର",
          ml: "മാപ്പുകൾ",
          pa: "ਨਕਸ਼ੇ",
        },
        route: "/map",
        colorClass: "icon-olive",
      },
      {
        id: "training",
        icon: GraduationCap,
        label: {
          en: "Training",
          ar: "التدريب",
          ur: "تربیت",
          hi: "प्रशिक्षण",
          ta: "பயிற்சி",
          te: "శిక్షణ",
          mr: "प्रशिक्षण",
          bn: "প্রশিক্ষণ",
          or: "ତାଲିମ",
          ml: "പരിശീലനം",
          pa: "ਸਿਖਲਾਈ",
        },
        route: "/shi-training",
        colorClass: "icon-plum",
      },
      {
        id: "sukoon-rd",
        icon: ShieldCheck,
        label: {
          en: "Sukoon RD",
          ar: "سكون RD",
          ur: "سکون RD",
          hi: "सुकून RD",
          ta: "சுகூன் RD",
          te: "సుకూన్ RD",
          mr: "सुकून RD",
          bn: "সুকুন RD",
          or: "ସୁକୁନ RD",
          ml: "സുകൂൺ RD",
          pa: "ਸੁਕੂਨ RD",
        },
        route: "/sukoon-rd",
        colorClass: "icon-emerald",
      },
      {
        id: "assistant",
        icon: Bot,
        label: {
          en: "AI Assistant",
          ar: "المساعد الذكي",
          ur: "اے آئی",
          hi: "AI सहायक",
          ta: "AI உதவி",
          te: "AI సహాయం",
          mr: "AI मदत",
          bn: "AI সহায়ক",
          or: "AI ସହାୟକ",
          ml: "AI സഹായി",
          pa: "AI ਸਹਾਇਕ",
        },
        route: "/chat",
        colorClass: "icon-teal",
      },
    ],
  },
  // SECTION B – CORE JOURNEY
  {
    id: "core-journey",
    title: {
      en: "Core Journey",
      ar: "الرحلة الأساسية",
      ur: "اصل سفر",
      hi: "मुख्य यात्रा",
      ta: "முக்கிய பயணம்",
      te: "ప్రధాన ప్రయాణం",
      mr: "मुख्य प्रवास",
      bn: "মূল যাত্রা",
      or: "ମୁଖ୍ୟ ଯାତ୍ରା",
      ml: "പ്രധാന യാത്ര",
      pa: "ਮੁੱਖ ਯਾਤਰਾ",
    },
    items: [
      {
        id: "makkah",
        icon: Building,
        label: {
          en: "Makkah",
          ar: "مكة",
          ur: "مکہ",
          hi: "मक्का",
          ta: "மக்கா",
          te: "మక్కా",
          mr: "मक्का",
          bn: "মক্কা",
          or: "ମକ୍କା",
          ml: "മക്ക",
          pa: "ਮੱਕਾ",
        },
        route: "/makkah-guide",
        colorClass: "icon-gold",
      },
      {
        id: "madinah",
        icon: MapPin,
        label: {
          en: "Madinah",
          ar: "المدينة",
          ur: "مدینہ",
          hi: "मदीना",
          ta: "மதீனா",
          te: "మదీనా",
          mr: "मदीना",
          bn: "মদিনা",
          or: "ମଦୀନା",
          ml: "മദീന",
          pa: "ਮਦੀਨਾ",
        },
        route: "/madinah-guide",
        colorClass: "icon-emerald",
      },
      {
        id: "umrah",
        icon: Moon,
        label: {
          en: "Umrah",
          ar: "العمرة",
          ur: "عمرہ",
          hi: "उमराह",
          ta: "உம்ரா",
          te: "ఉమ్రా",
          mr: "उमराह",
          bn: "উমরাহ",
          or: "ଉମରାହ",
          ml: "ഉംറ",
          pa: "ਉਮਰਾਹ",
        },
        route: "/umrah",
        colorClass: "icon-sage",
      },
      {
        id: "hajj",
        icon: Landmark,
        label: {
          en: "Hajj",
          ar: "الحج",
          ur: "حج",
          hi: "हज",
          ta: "ஹஜ்",
          te: "హజ్",
          mr: "हज",
          bn: "হজ",
          or: "ହଜ୍ଜ",
          ml: "ഹജ്ജ്",
          pa: "ਹੱਜ",
        },
        route: "/prepare",
        colorClass: "icon-teal",
      },
      {
        id: "qurbani",
        icon: Sword,
        label: {
          en: "Qurbani",
          ar: "قربانی",
          ur: "قربانی",
          hi: "कुर्बानी",
          ta: "குர்பானி",
          te: "ఖుర్బానీ",
          mr: "कुर्बानी",
          bn: "কোরবানি",
          or: "କୁର୍ବାନୀ",
          ml: "ഖുർബാനി",
          pa: "ਕੁਰਬਾਨੀ",
        },
        route: "/qurbani",
        colorClass: "icon-sand",
      },
      {
        id: "dua",
        icon: HandHeart,
        label: {
          en: "Duas",
          ar: "الدعاء",
          ur: "دعائیں",
          hi: "दुआएं",
          ta: "துஆக்கள்",
          te: "దుఆలు",
          mr: "दुआ",
          bn: "দোয়া",
          or: "ଦୁଆ",
          ml: "ദുആകൾ",
          pa: "ਦੁਆਵਾਂ",
        },
        route: "/dua",
        colorClass: "icon-plum",
      },
    ],
  },
  // SECTION C – SPECIAL
  {
    id: "special",
    title: {
      en: "Special",
      ar: "خاص",
      ur: "خاص",
      hi: "विशेष",
      ta: "சிறப்பு",
      te: "ప్రత్యేక",
      mr: "विशेष",
      bn: "বিশেষ",
      or: "ବିଶେଷ",
      ml: "പ്രത്യേക",
      pa: "ਵਿਸ਼ੇਸ਼",
    },
    items: [
      {
        id: "women",
        icon: Flower2,
        label: {
          en: "Women",
          ar: "النساء",
          ur: "خواتین",
          hi: "महिलाएं",
          ta: "பெண்கள்",
          te: "మహిళలు",
          mr: "महिला",
          bn: "মহিলা",
          or: "ମହିଳା",
          ml: "സ്ത്രീകൾ",
          pa: "ਔਰਤਾਂ",
        },
        route: "/women",
        colorClass: "icon-rose",
      },
      {
        id: "services",
        icon: HeartHandshake,
        label: {
          en: "Services",
          ar: "الخدمات",
          ur: "خدمات",
          hi: "सेवाएं",
          ta: "சேவைகள்",
          te: "సేవలు",
          mr: "सेवा",
          bn: "সেবা",
          or: "ସେବା",
          ml: "സേവനങ്ങൾ",
          pa: "ਸੇਵਾਵਾਂ",
        },
        route: "/govt-services",
        colorClass: "icon-teal",
      },
      {
        id: "food",
        icon: UtensilsCrossed,
        label: {
          en: "Food",
          ar: "الطعام",
          ur: "کھانا",
          hi: "भोजन",
          ta: "உணவு",
          te: "ఆహారం",
          mr: "अन्न",
          bn: "খাবার",
          or: "ଖାଦ୍ୟ",
          ml: "ഭക്ഷണം",
          pa: "ਭੋਜਨ",
        },
        route: "/food",
        colorClass: "icon-sand",
      },
      {
        id: "family",
        icon: Users,
        label: {
          en: "Family",
          ar: "العائلة",
          ur: "خاندان",
          hi: "परिवार",
          ta: "குடும்பம்",
          te: "కుటుంబం",
          mr: "कुटुंब",
          bn: "পরিবার",
          or: "ପରିବାର",
          ml: "കുടുംബം",
          pa: "ਪਰਿਵਾਰ",
        },
        route: "/family",
        colorClass: "icon-sky",
      },
      {
        id: "family-progress",
        icon: Route,
        label: {
          en: "Hajj Progress",
          ar: "تقدم الحج",
          ur: "حج پیشرفت",
          hi: "हज प्रगति",
          ta: "ஹஜ் முன்னேற்றம்",
          te: "హజ్ ప్రగతి",
          mr: "हज प्रगती",
          bn: "হজ অগ্রগতি",
          or: "ହଜ୍ଜ ପ୍ରଗତି",
          ml: "ഹജ്ജ് പുരോഗതി",
          pa: "ਹੱਜ ਪ੍ਰਗਤੀ",
        },
        route: "/hajj-progress",
        colorClass: "icon-emerald",
      },
      {
        id: "socials",
        icon: MessageCircle,
        label: {
          en: "Socials",
          ar: "التواصل",
          ur: "سوشل",
          hi: "सोशल",
          ta: "சமூகம்",
          te: "సోషల్స్",
          mr: "सोशल",
          bn: "সোশ্যাল",
          or: "ସୋସିଆଲ",
          ml: "സോഷ്യൽ",
          pa: "ਸੋਸ਼ਲ",
        },
        route: "/socials",
        colorClass: "icon-plum",
      },
      {
        id: "payment",
        icon: CreditCard,
        label: {
          en: "Service Fees",
          ar: "رسوم الخدمة",
          ur: "سروس فیس",
          hi: "सेवा शुल्क",
          ta: "சேவைக் கட்டணம்",
          te: "సేవా రుసుము",
          mr: "सेवा शुल्क",
          bn: "সেবা ফি",
          or: "ସେବା ଶୁଳ୍କ",
          ml: "സേവന ഫീസ്",
          pa: "ਸੇਵਾ ਫੀਸ",
        },
        route: "/payment",
        colorClass: "icon-olive",
      },
      {
        id: "rewards",
        icon: Wallet,
        label: {
          en: "Rewards & Wallet",
          ar: "المكافآت والمحفظة",
          ur: "انعامات اور والیٹ",
          hi: "रिवॉर्ड्स और वॉलेट",
          ta: "வெகுமதிகள்",
          te: "రివార్డ్స్",
          mr: "बक्षीस व वॉलेट",
          bn: "পুরস্কার ও ওয়ালেট",
          or: "ପୁରସ୍କାର ଓ ୱାଲେଟ",
          ml: "റിവാർഡ്സ് & വാലറ്റ്",
          pa: "ਇਨਾਮ ਅਤੇ ਵਾਲਿਟ",
        },
        route: "/rewards",
        colorClass: "icon-gold",
      },
      {
        id: "video-call",
        icon: Video,
        label: {
          en: "Video Call",
          ar: "مكالمة فيديو",
          ur: "ویڈیو کال",
          hi: "वीडियो कॉल",
          ta: "வீடியோ அழைப்பு",
          te: "వీడియో కాల్",
          mr: "व्हिडिओ कॉल",
          bn: "ভিডিও কল",
          or: "ଭିଡିଓ କଲ",
          ml: "വീഡിയോ കോൾ",
          pa: "ਵੀਡੀਓ ਕਾਲ",
        },
        route: "/video-call",
        colorClass: "icon-plum",
      },
    ],
  },
  // SECTION D – HELP
  {
    id: "help-section",
    title: {
      en: "Help",
      ar: "مساعدة",
      ur: "مدد",
      hi: "मदद",
      ta: "உதவி",
      te: "సహాయం",
      mr: "मदत",
      bn: "সাহায্য",
      or: "ସାହାଯ୍ୟ",
      ml: "സഹായം",
      pa: "ਮਦਦ",
    },
    items: [
      {
        id: "grievances",
        icon: AlertTriangle,
        label: {
          en: "Grievance",
          ar: "الشكاوى",
          ur: "شکایات",
          hi: "शिकायतें",
          ta: "புகார்",
          te: "ఫిర్యాదు",
          mr: "तक्रार",
          bn: "অভিযোগ",
          or: "ଅଭିଯୋଗ",
          ml: "പരാതി",
          pa: "ਸ਼ਿਕਾਇਤ",
        },
        route: "/grievances",
        colorClass: "icon-coral",
      },
      {
        id: "medical",
        icon: Stethoscope,
        label: {
          en: "Medical Help",
          ar: "المساعدة الطبية",
          ur: "طبی مدد",
          hi: "चिकित्सा सहायता",
          ta: "மருத்துவ உதவி",
          te: "వైద్య సహాయం",
          mr: "वैद्यकीय मदत",
          bn: "চিকিৎসা সাহায্য",
          or: "ଚିକିତ୍ସା ସହାୟତା",
          ml: "വൈദ്യ സഹായം",
          pa: "ਮੈਡੀਕਲ ਮਦਦ",
        },
        route: "/help",
        colorClass: "icon-emerald",
      },
      {
        id: "directory",
        icon: Phone,
        label: {
          en: "Directory",
          ar: "الدليل",
          ur: "ڈائریکٹری",
          hi: "डायरेक्टरी",
          ta: "அடைவு",
          te: "డైరెక్టరీ",
          mr: "डायरेक्टरी",
          bn: "ডিরেক্টরি",
          or: "ଡିରେକ୍ଟୋରୀ",
          ml: "ഡയറക്ടറി",
          pa: "ਡਾਇਰੈਕਟਰੀ",
        },
        route: "/haj-directory",
        colorClass: "icon-teal",
      },
    ],
  },
  // SECTION E – AFTER HAJJ
  {
    id: "after-hajj",
    title: {
      en: "After Hajj",
      ar: "بعد الحج",
      ur: "حج کے بعد",
      hi: "हज के बाद",
      ta: "ஹஜ்ஜுக்கு பின்",
      te: "హజ్ తర్వాత",
      mr: "हज नंतर",
      bn: "হজের পর",
      or: "ହଜ ପରେ",
      ml: "ഹജ്ജിന് ശേഷം",
      pa: "ਹੱਜ ਤੋਂ ਬਾਅਦ",
    },
    items: [
      {
        id: "post-hajj",
        icon: Star,
        label: {
          en: "Hajj Mabroor",
          ar: "حج مبرور",
          ur: "حج مبرور",
          hi: "हज मबरूर",
          ta: "ஹஜ் மப்ரூர்",
          te: "హజ్ మబ్రూర్",
          mr: "हज मबरूर",
          bn: "হজ মাবরুর",
          or: "ହଜ ମବ୍ରୁର",
          ml: "ഹജ്ജ് മബ്റൂർ",
          pa: "ਹੱਜ ਮਬਰੂਰ",
        },
        route: "/post-hajj",
        colorClass: "icon-gold",
      },
      {
        id: "free-umrah",
        icon: Gift,
        label: {
          en: "Free Umrah",
          ar: "عمرة مجانية",
          ur: "مفت عمرہ",
          hi: "मुफ्त उमराह",
          ta: "இலவச உம்ரா",
          te: "ఉచిత ఉమ్రా",
          mr: "मोफत उमराह",
          bn: "বিনামূল্যে উমরাহ",
          or: "ମାଗଣା ଉମରାହ",
          ml: "സൗജന്യ ഉംറ",
          pa: "ਮੁਫ਼ਤ ਉਮਰਾਹ",
        },
        route: "/free-umrah",
        colorClass: "icon-emerald",
      },
      {
        id: "support",
        icon: Headphones,
        label: {
          en: "Support",
          ar: "الدعم",
          ur: "سپورٹ",
          hi: "सहायता",
          ta: "ஆதரவு",
          te: "మద్దతు",
          mr: "समर्थन",
          bn: "সমর্থন",
          or: "ସମର୍ଥନ",
          ml: "പിന്തുണ",
          pa: "ਸਹਾਇਤਾ",
        },
        route: "/contact-us",
        colorClass: "icon-sage",
      },
    ],
  },
];
