
ALTER TABLE public.haj_inspectors
  ADD COLUMN IF NOT EXISTS whatsapp TEXT,
  ADD COLUMN IF NOT EXISTS flight_schedule TEXT,
  ADD COLUMN IF NOT EXISTS emergency_control_room_no TEXT,
  ADD COLUMN IF NOT EXISTS total_haji_quota INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_hajis INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_groups INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_group_leaders INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_doctors INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_buildings INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS live_emergency_cases INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS live_complaints INTEGER DEFAULT 0;
