// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const configuredUrl = import.meta.env.VITE_SUPABASE_URL?.trim();
const configuredKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY?.trim();

const isHttpUrl = (value: string | undefined): value is string => {
  if (!value) return false;

  try {
    const url = new URL(value);
    return url.protocol === "https:" || url.protocol === "http:";
  } catch {
    return false;
  }
};

/**
 * Keep public, offline-first pages available when a deployment is missing its
 * Supabase environment variables. Network-backed actions will fail normally,
 * but a malformed URL must never prevent the entire React app from mounting.
 */
export const isSupabaseConfigured = isHttpUrl(configuredUrl) && Boolean(configuredKey);
const SUPABASE_URL = isSupabaseConfigured
  ? configuredUrl
  : "https://offline.hajjcare.invalid";
const SUPABASE_PUBLISHABLE_KEY = isSupabaseConfigured
  ? configuredKey
  : "offline-public-key";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
